# Combining PM2.5 EPA Air Quality Data and Calculating Annual Averages for the Largest and Fastest-Growing Metro Areas

In [173]:
import pandas as pd

## Here I combine PM2.5 air quality monitoring data from 1980-2025 from the EPA

In [174]:
df = pd.read_csv('daily_88101_2024.csv')

/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1788329595.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('daily_88101_2024.csv')

In [175]:
pd.set_option('display.max_columns', None)

In [176]:
md_24 = df[df['State Name'] == 'Maryland']

In [177]:
import pandas as pd

all_data = []  # list to collect each year's data

for year in range(1980, 2025):
    filename = f'daily_88101_{year}.csv'
    try:
        df = pd.read_csv(filename)
        all_data.append(df)
    except FileNotFoundError:
        print(f"File not found: {filename}")

# Concatenate all years into a single DataFrame
all_years_df = pd.concat(all_data, ignore_index=True)

/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (13,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/2173117846.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_years_df = pd.concat(all_data, ignore_index=True)

In [178]:
all_years_df['Sample Duration'].value_counts()

Sample Duration
1 HOUR           3132921
24-HR BLK AVG    3074694
24 HOUR          2966290
Name: count, dtype: int64

In [179]:
all_years_df.shape

(9173905, 29)

In [180]:
all_years_df[all_years_df['Sample Duration'] == '24 HOUR'].sort_values(by='Date Local',ascending=False)

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
8884023,19,153,30,88101,1,41.603159,-93.643118,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),NaN,1,100.0,2.4,2.4,0,13.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,CARPENTER,"1907 CARPENTER, DES MOINES IOWA",Iowa,Polk,Des Moines,"Des Moines-West Des Moines, IA",2024-11-19
8884022,19,153,30,88101,1,41.603159,-93.643118,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,2024-10-30,Micrograms/cubic meter (LC),NaN,1,100.0,7.0,7.0,0,39.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,CARPENTER,"1907 CARPENTER, DES MOINES IOWA",Iowa,Polk,Des Moines,"Des Moines-West Des Moines, IA",2024-11-19
8885378,19,153,5885,88101,1,41.667032,-93.599221,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,2024-10-30,Micrograms/cubic meter (LC),NaN,1,100.0,7.5,7.5,0,42.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,"PUBLIC WORKS, DES MOINES IA, FRM, SEQ. SAMPLER...",5885 NE 14TH ST,Iowa,Polk,Des Moines,"Des Moines-West Des Moines, IA",2024-11-19
8884021,19,153,30,88101,1,41.603159,-93.643118,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,2024-10-29,Micrograms/cubic meter (LC),NaN,1,100.0,7.6,7.6,0,42.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,CARPENTER,"1907 CARPENTER, DES MOINES IOWA",Iowa,Polk,Des Moines,"Des Moines-West Des Moines, IA",2024-11-19
8884020,19,153,30,88101,1,41.603159,-93.643118,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,2024-10-28,Micrograms/cubic meter (LC),NaN,1,100.0,9.9,9.9,0,52.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,CARPENTER,"1907 CARPENTER, DES MOINES IOWA",Iowa,Polk,Des Moines,"Des Moines-West Des Moines, IA",2024-11-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,55,133,27,88101,1,43.020075,-88.215070,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-16,Micrograms/cubic meter (LC),NaN,1,100.0,12.0,12.0,0,56.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,WAUKESHA - CLEVELAND AVE,1310 CLEVELAND AVE,Wisconsin,Waukesha,Waukesha,"Milwaukee-Waukesha-West Allis, WI",2024-05-19
42,55,79,10,88101,1,43.017240,-87.933690,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-10,Micrograms/cubic meter (LC),NaN,1,100.0,22.0,22.0,0,75.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,MILWAUKEE - SIXTEENTH ST. HEALTH CENTER,"HEALTH CENTER, 1337 SO 16TH ST",Wisconsin,Milwaukee,Milwaukee,"Milwaukee-Waukesha-West Allis, WI",2024-05-19
86,55,133,27,88101,1,43.020075,-88.215070,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-10,Micrograms/cubic meter (LC),NaN,1,100.0,25.0,25.0,0,81.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,WAUKESHA - CLEVELAND AVE,1310 CLEVELAND AVE,Wisconsin,Waukesha,Waukesha,"Milwaukee-Waukesha-West Allis, WI",2024-05-19
85,55,133,27,88101,1,43.020075,-88.215070,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-04,Micrograms/cubic meter (LC),NaN,1,100.0,31.0,31.0,0,92.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,WAUKESHA - CLEVELAND AVE,1310 CLEVELAND AVE,Wisconsin,Waukesha,Waukesha,"Milwaukee-Waukesha-West Allis, WI",2024-05-19
41,55,79,10,88101,1,43.017240,-87.933690,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-04,Micrograms/cubic meter (LC),NaN,1,100.0,50.0,50.0,0,137.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,MILWAUKEE - SIXTEENTH ST. HEALTH CENTER,"HEALTH CENTER, 1337 SO 16TH ST",Wisconsin,Milwaukee,Milwaukee,"Milwaukee-Waukesha-West Allis, WI",2024-05-19

In [181]:
all_years_df[all_years_df['Sample Duration'] == '24-HR BLK AVG'].sort_values(by='Date Local')

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
1362891,15,1,1012,88101,1,19.509778,-155.913417,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2008-03-15,Micrograms/cubic meter (LC),NaN,1,100.0,20.5,20.5,0,72.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Kona,81-1043 KONAWAENA SCHOOL RD,Hawaii,Hawaii,Kealakekua,"Hilo, HI",2024-05-21
1362892,15,1,1012,88101,1,19.509778,-155.913417,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2008-03-16,Micrograms/cubic meter (LC),NaN,1,100.0,16.7,16.7,0,65.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Kona,81-1043 KONAWAENA SCHOOL RD,Hawaii,Hawaii,Kealakekua,"Hilo, HI",2024-05-21
1362893,15,1,1012,88101,1,19.509778,-155.913417,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2008-03-17,Micrograms/cubic meter (LC),NaN,1,100.0,14.0,14.0,0,60.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Kona,81-1043 KONAWAENA SCHOOL RD,Hawaii,Hawaii,Kealakekua,"Hilo, HI",2024-05-21
1362894,15,1,1012,88101,1,19.509778,-155.913417,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2008-03-18,Micrograms/cubic meter (LC),NaN,1,100.0,19.0,19.0,0,69.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Kona,81-1043 KONAWAENA SCHOOL RD,Hawaii,Hawaii,Kealakekua,"Hilo, HI",2024-05-21
1362895,15,1,1012,88101,1,19.509778,-155.913417,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2008-03-19,Micrograms/cubic meter (LC),NaN,1,100.0,19.6,19.6,0,71.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Kona,81-1043 KONAWAENA SCHOOL RD,Hawaii,Hawaii,Kealakekua,"Hilo, HI",2024-05-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8761971,6,23,6,88101,3,41.047117,-123.675233,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),Included,1,100.0,12.0,12.0,0,56.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Hoopa Valley Reservation,"5 Loop Rd Hoopa, CA 95546",California,Humboldt,Not in a city,"Eureka-Arcata-Fortuna, CA",2024-11-05
8900507,22,51,2001,88101,3,29.900314,-90.109836,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),NaN,2,200.0,7.4,7.4,0,41.0,236,Teledyne T640 at 5.0 LPM - Broadband spectroscopy,Marrero,328 Marrero Road,Louisiana,Jefferson,Marrero,"New Orleans-Metairie, LA",2024-11-18
9099806,47,157,75,88101,3,35.151699,-89.850249,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),NaN,4,400.0,10.8,10.8,0,54.0,238,Teledyne T640X at 16.67 LPM - Broadband spectr...,Memphis NCORE site,6388 Haley Rd. (Shelby Farms NCORE site),Tennessee,Shelby,Memphis,"Memphis, TN-MS-AR",2024-11-07
8883056,19,113,40,88101,4,41.976770,-91.687660,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),NaN,3,300.0,2.1,2.1,0,12.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Public Health,500 11TH ST NW,Iowa,Linn,Cedar Rapids,"Cedar Rapids, IA",2024-11-12
8906770,23,5,15,88101,2,43.677994,-70.256178,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-10-31,Micrograms/cubic meter (LC),NaN,2,200.0,10.8,10.8,0,54.0,238,Teledyne T640X at 16.67 LPM - Broadband spectr...,TB - Tukey's Bridge,TUKEY'S BRIDGE-BEAN POT RD.,Maine,Cumberland,Portland,"Portland-South Portland, ME",2024-11-01

In [182]:
all_years_df['Date Local'] = pd.to_datetime(all_years_df['Date Local'])
all_years_df['Year'] = all_years_df['Date Local'].dt.year

In [183]:
all_years_df[all_years_df['Sample Duration'] == '24-HR BLK AVG']['Year'].value_counts().reset_index().sort_values(by='Year')

    Year   count
16  2008    3445
15  2009   25795
14  2010   49258
13  2011   70456
12  2012   82525
11  2013  103460
10  2014  119249
9   2015  128439
8   2016  147653
7   2017  177733
5   2018  230396
4   2019  283049
3   2020  313279
2   2021  358567
0   2022  395715
1   2023  388950
6   2024  196725

In [184]:
all_years_df[all_years_df['Sample Duration'] == '24 HOUR']['Year'].value_counts().reset_index().sort_values(by='Year')

    Year   count
27  1997     128
26  1998     625
17  1999  103210
2   2000  153561
1   2001  166081
0   2002  168064
3   2003  150587
4   2004  149281
5   2005  145913
8   2006  139281
6   2007  145631
7   2008  140126
9   2009  138841
10  2010  130045
13  2011  108527
15  2012  107843
14  2013  107899
16  2014  107562
11  2015  113356
12  2016  109280
18  2017   99821
19  2018   90746
20  2019   83154
21  2020   72400
22  2021   67767
23  2022   66702
24  2023   63204
25  2024   36655

## I created a sub-dataset for Maryland-data here

In [185]:
import pandas as pd

all_md_data = []  # list to collect each year's filtered data

for year in range(1980, 2025):
    filename = f'daily_88101_{year}.csv'
    try:
        df = pd.read_csv(filename)
        md_year = df[df['State Name'] == 'Maryland']
        all_md_data.append(md_year)
    except FileNotFoundError:
        print(f"File not found: {filename}")

# Concatenate all years into a single DataFrame
maryland_df = pd.concat(all_md_data, ignore_index=True)

/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (13,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/1636041407.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  maryland_df = pd.concat(all_md_data, ignore_index=True)

In [186]:
maryland_df

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,24,3,14,88101,1,38.90250,-76.653056,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1999-08-07,Micrograms/cubic meter (LC),NaN,1,100.0,24.1,24.1,0,79.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Davidsonville,"Davidsonville Recreation Center, 3801 Queen A...",Maryland,Anne Arundel,Not in a city,"Baltimore-Columbia-Towson, MD",2024-05-19
1,24,3,14,88101,1,38.90250,-76.653056,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1999-08-10,Micrograms/cubic meter (LC),NaN,1,100.0,15.9,15.9,0,64.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Davidsonville,"Davidsonville Recreation Center, 3801 Queen A...",Maryland,Anne Arundel,Not in a city,"Baltimore-Columbia-Towson, MD",2024-05-19
2,24,3,14,88101,1,38.90250,-76.653056,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1999-08-13,Micrograms/cubic meter (LC),NaN,1,100.0,29.1,29.1,0,88.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Davidsonville,"Davidsonville Recreation Center, 3801 Queen A...",Maryland,Anne Arundel,Not in a city,"Baltimore-Columbia-Towson, MD",2024-05-19
3,24,3,14,88101,1,38.90250,-76.653056,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1999-08-16,Micrograms/cubic meter (LC),NaN,1,100.0,18.4,18.4,0,68.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Davidsonville,"Davidsonville Recreation Center, 3801 Queen A...",Maryland,Anne Arundel,Not in a city,"Baltimore-Columbia-Towson, MD",2024-05-19
4,24,3,14,88101,1,38.90250,-76.653056,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1999-08-19,Micrograms/cubic meter (LC),NaN,1,100.0,12.2,12.2,0,57.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Davidsonville,"Davidsonville Recreation Center, 3801 Queen A...",Maryland,Anne Arundel,Not in a city,"Baltimore-Columbia-Towson, MD",2024-05-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144548,24,510,5253,88101,3,39.33746,-76.589050,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-09-26,Micrograms/cubic meter (LC),NaN,1,100.0,3.0,3.0,0,17.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Lake Montebello,3900 Hillen Road,Maryland,Baltimore (City),Baltimore,"Baltimore-Columbia-Towson, MD",2024-10-29
144549,24,510,5253,88101,3,39.33746,-76.589050,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-09-27,Micrograms/cubic meter (LC),NaN,1,100.0,0.4,0.4,0,2.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Lake Montebello,3900 Hillen Road,Maryland,Baltimore (City),Baltimore,"Baltimore-Columbia-Towson, MD",2024-10-29
144550,24,510,5253,88101,3,39.33746,-76.589050,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-09-28,Micrograms/cubic meter (LC),NaN,1,100.0,1.3,1.3,0,7.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Lake Montebello,3900 Hillen Road,Maryland,Baltimore (City),Baltimore,"Baltimore-Columbia-Towson, MD",2024-10-29
144551,24,510,5253,88101,3,39.33746,-76.589050,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-09-29,Micrograms/cubic meter (LC),NaN,1,100.0,2.1,2.1,0,12.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Lake Montebello,3900 Hillen Road,Maryland,Baltimore (City),Baltimore,"Baltimore-Columbia-Towson, MD",2024-10-29
144552,24,510,5253,88101,3,39.33746,-76.589050,NAD83,PM2.5 - Local Conditions,24-HR BLK AVG,PM25 24-hour 2012,2024-09-30,Micrograms/cubic meter (LC),NaN,1,100.0,4.1,4.1,0,23.0,170,Met One BAM-1020 Mass Monitor w/VSCC - Beta At...,Lake Montebello,3900 Hillen Road,Maryland,Baltimore (City),Baltimore,"Baltimore-Columbia-Towson, MD",2024-10-29

In [187]:
maryland_df['Local Site Name'].value_counts()

Local Site Name
Oldtown                                                                 15768
HU-Beltsville                                                           13362
Fair Hill Natural Resource Management Area                              12603
Rockville                                                               12371
Hagerstown                                                              11096
Edgewood                                                                10583
Millington                                                              10060
Piney Run                                                                9617
Horn Point                                                               8768
Padonia                                                                  8042
Howard County Near Road                                                  7265
Essex                                                                    4658
FMC-Fairfield                                                            3239
GLEN BURNIE                                                              2400
Northwest Police Station                                                 2310
PG Equestrian Center                                                     2275
Lake Montebello                                                          2207
BCFD-TRUCK COMPANY 20                                                    1994
Northeast Police                                                         1365
 Davidsonville                                                            680
WESTPORT LAT/LONG POINT IS OF SAMPLING INLET                              660
Bladensburg VFC                                                           573
FT MEADE LAT/LONG POINT IS OF THE SAMPLING INLET                          552
LAT/LONG POINT IS OF SAMPLING INLET.................................      443
PM10S MOVED FROM HOLABIRD E.S. TO BROENING HWY FIRE STATION #50           188
Name: count, dtype: int64

In [188]:
daily_avg = maryland_df[maryland_df['Sample Duration'] == '24-HR BLK AVG']

In [189]:
daily_avg['Local Site Name'].value_counts()

Local Site Name
Fair Hill Natural Resource Management Area    5635
Rockville                                     5481
HU-Beltsville                                 5241
Millington                                    4970
Hagerstown                                    4849
Piney Run                                     4709
Oldtown                                       4685
Edgewood                                      4595
Horn Point                                    4334
Howard County Near Road                       3582
Padonia                                       2744
Lake Montebello                                947
Name: count, dtype: int64

## I read in the census data on top fastest-growing large metro areas here from the other notebook

In [190]:
metros = pd.read_csv('fastest_growing_large_metros.csv')

In [191]:
metros

,metro_area_2010,population_2014,matched_metro_area_2023,match_score,population_2023,pop_pct_change
0,"Austin-Round Rock, TX",1835016,"Austin-Round Rock-San Marcos, TX",75.471698,2357497,0.284728
1,"Fresno, CA",948844,"Fresno, CA",100.000000,1170942,0.234072
2,"Orlando-Kissimmee-Sanford, FL",2226835,"Orlando-Kissimmee-Sanford, FL",100.000000,2721022,0.221923
3,"Raleigh, NC",1189579,"Raleigh-Cary, NC",81.481481,1449594,0.218577
4,"Jacksonville, FL",1380995,"Jacksonville, FL",100.000000,1645707,0.191682
5,"Nashville-Davidson--Murfreesboro--Franklin, TN",1730515,"Nashville-Davidson--Murfreesboro--Franklin, TN",100.000000,2043713,0.180985
6,"Charlotte-Concord-Gastonia, NC-SC",2298915,"Charlotte-Concord-Gastonia, NC-SC",100.000000,2712818,0.180043
7,"Houston-The Woodlands-Sugar Land, TX",6204141,"Houston-Pasadena-The Woodlands, TX",68.571429,7274714,0.172558
8,"San Antonio-New Braunfels, TX",2239222,"San Antonio-New Braunfels, TX",100.000000,2612802,0.166835
9,"Dallas-Fort Worth-Arlington, TX",6703020,"Dallas-Fort Worth-Arlington, TX",100.000000,7807555,0.164782
10,"Grand Rapids-Wyoming, MI",1007329,"Grand Rapids-Wyoming-Kentwood, MI",84.210526,1154320,0.145922
11,"Phoenix-Mesa-Scottsdale, AZ",4337542,"Phoenix-Mesa-Chandler, AZ",76.923077,4941206,0.139172
12,"Tampa-St. Petersburg-Clearwater, FL",2851235,"Tampa-St. Petersburg-Clearwater, FL",100.000000,3240469,0.136514
13,"Atlanta-Sandy Springs-Roswell, GA",5455053,"Atlanta-Sandy Springs-Roswell, GA",100.000000,6176937,0.132333
14,"Seattle-Tacoma-Bellevue, WA",3557037,"Seattle-Tacoma-Bellevue, WA",100.000000,4021467,0.130567
15,"Salt Lake City, UT",1123643,"Salt Lake City-Murray, UT",83.720930,1261337,0.122542
16,"Oklahoma City, OK",1297998,"Oklahoma City, OK",100.000000,1445122,0.113347
17,"Columbus, OH",1948188,"Columbus, OH",100.000000,2151847,0.104538
18,"Portland-Vancouver-Hillsboro, OR-WA",2288796,"Portland-Vancouver-Hillsboro, OR-WA",100.000000,2510529,0.096878
19,"Sacramento--Roseville--Arden-Arcade, CA",2197422,"Sacramento-Roseville-Folsom, CA",71.428571,2406563,0.095176
20,"Indianapolis-Carmel-Anderson, IN",1931182,"Indianapolis-Carmel-Greenwood, IN",80.000000,2106327,0.090693
21,"Louisville/Jefferson County, KY-IN",1253305,"Louisville/Jefferson County, KY-IN",100.000000,1361847,0.086605
22,"Kansas City, MO-KS",2040869,"Kansas City, MO-KS",100.000000,2202006,0.078955
23,"Minneapolis-St. Paul-Bloomington, MN-WI",3424786,"Minneapolis-St. Paul-Bloomington, MN-WI",100.000000,3693351,0.078418
24,"Tulsa, OK",954055,"Tulsa, OK",100.000000,1026209,0.075629
25,"Richmond, VA",1234058,"Richmond, VA",100.000000,1327321,0.075574
26,"Washington-Arlington-Alexandria, DC-VA-MD-WV",5863608,"Washington-Arlington-Alexandria, DC-VA-MD-WV",100.000000,6263796,0.068249
27,"Riverside-San Bernardino-Ontario, CA",4345485,"Riverside-San Bernardino-Ontario, CA",100.000000,4637725,0.067251
28,"Miami-Fort Lauderdale-West Palm Beach, FL",5775204,"Miami-Fort Lauderdale-West Palm Beach, FL",100.000000,6138876,0.062971
29,"Cincinnati, OH-KY-IN",2131793,"Cincinnati, OH-KY-IN",100.000000,2255257,0.057916
30,"Boston-Cambridge-Newton, MA-NH",4650876,"Boston-Cambridge-Newton, MA-NH",100.000000,4917661,0.057362
31,"Tucson, AZ",993144,"Tucson, AZ",100.000000,1049947,0.057195
32,"Cleveland-Elyria, OH",2067490,"Cleveland, OH",78.787879,2171978,0.050539
33,"Virginia Beach-Norfolk-Newport News, VA-NC",1697898,"Virginia Beach-Chesapeake-Norfolk, VA-NC",70.731707,1782590,0.049880
34,"Providence-Warwick, RI-MA",1604317,"Providence-Warwick, RI-MA",100.000000,1673807,0.043314
35,"San Francisco-Oakland-Hayward, CA",4466251,"San Francisco-Oakland-Fremont, CA",81.818182,4653593,0.041946
36,"Birmingham-Hoover, AL",1135534,"Birmingham, AL",80.000000,1181432,0.040420
37,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",6015336,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",100.000000,6241882,0.037661
38,"San Jose-Sunnyvale-Santa Clara, CA",1898457,"San Jose-Sunnyvale-Santa Clara, CA",100.000000,1969353,0.037344
39,"Pittsburgh, PA",2358793,"Pittsburgh, PA",100.000000,2443921,0.036090
40,"Baltimore-Columbia-Towson, MD",2753396,"Baltimore-Columbia-Towson, MD",100.000000,2839409,0.031239
41,"Urban Honolulu, HI",975690,"Urban Honolulu, HI",100.000000,1003666,0.028673
42,"Buffalo-Cheektowaga-Niagara Falls, NY",1135667,"Buffalo-Cheektowaga, NY",76.666667,1161385,0.022646
43,"Detroit-Warren-Dearborn, MI",4292647,"Detroit-Warren-Dearborn, MI",100.000000,4367620,0.017465
44,"St. Louis, MO-IL",2797737,"St. Louis, MO-IL",100.000000,2809414,0.004174
45,"Memphis, TN-MS-AR",1337014,"Memphis, TN-MS-AR",100.000000,1341606,0.003435
46,"Milwaukee-Waukesha-West Allis, WI",1565368,"Milwaukee-Waukesha, WI",76.363636,1566361,0.000634
47,"Los Angeles-Long Beach-Anaheim, CA",13060534,"Los Angeles-Long Beach-Anaheim, CA",100.000000,13012469,-0.003680
48,"New York-Newark-Jersey City, NY-NJ-PA",19865045,"New York-Newark-Jersey City, NY-NJ",95.774648,19756722,-0.005453
49,"Chicago-Naperville-Elgin, IL-IN-WI",9516448,"Chicago-Naperville-Elgin, IL-IN",95.384615,9359555,-0.016487
50,"Rochester, NY",1082578,"Rochester, NY",100.000000,1058875,-0.021895
51,"Hartford-West Hartford-East Hartford, CT",1215159,"Hartford-West Hartford-East Hartford, CT",100.000000,1144012,-0.058550
52,"San Juan-Carolina-Caguas, PR",2297987,"San Juan-Bayamón-Caguas, PR",80.000000,2063795,-0.101912

## Fuzzy matching the CBSA names from both datasets

In [192]:
# Get unique CBSA names from the air quality data
cbsa_names = all_years_df['CBSA Name'].dropna().unique()

# Get metro names from your reference DataFrame
metro_names = metros['matched_metro_area_2023'].dropna().unique()

In [193]:
from fuzzywuzzy import process

In [194]:
# Create a mapping: each CBSA Name → best match in metros
fuzzy_matches = []
for name in cbsa_names:
    match, score = process.extractOne(name, metro_names)
    fuzzy_matches.append({'cbsa_name': name, 'matched_metro': match, 'score': score})

matches_df = pd.DataFrame(fuzzy_matches)

In [195]:
#pd.set_option('display.max_rows', None)

In [196]:
matches_df = matches_df[matches_df['score'] > 92].sort_values(by='score')

In [197]:
matches_df

,cbsa_name,matched_metro,score
0,"Chicago-Naperville-Elgin, IL-IN-WI","Chicago-Naperville-Elgin, IL-IN",95
334,"Salt Lake City, UT","Salt Lake City-Murray, UT",95
178,"Grand Rapids-Wyoming, MI","Grand Rapids-Wyoming-Kentwood, MI",95
255,"Raleigh, NC","Raleigh-Cary, NC",95
221,"New York-Newark-Jersey City, NY-NJ-PA","New York-Newark-Jersey City, NY-NJ",96
169,"Boston-Cambridge-Newton, MA-NH","Boston-Cambridge-Newton, MA-NH",100
179,"Detroit-Warren-Dearborn, MI","Detroit-Warren-Dearborn, MI",100
184,"Minneapolis-St. Paul-Bloomington, MN-WI","Minneapolis-St. Paul-Bloomington, MN-WI",100
234,"Rochester, NY","Rochester, NY",100
241,"Charlotte-Concord-Gastonia, NC-SC","Charlotte-Concord-Gastonia, NC-SC",100
262,"Columbus, OH","Columbus, OH",100
270,"Oklahoma City, OK","Oklahoma City, OK",100
282,"Tulsa, OK","Tulsa, OK",100
284,"Portland-Vancouver-Hillsboro, OR-WA","Portland-Vancouver-Hillsboro, OR-WA",100
296,"Pittsburgh, PA","Pittsburgh, PA",100
318,"Nashville-Davidson--Murfreesboro--Franklin, TN","Nashville-Davidson--Murfreesboro--Franklin, TN",100
325,"San Antonio-New Braunfels, TX","San Antonio-New Braunfels, TX",100
328,"Dallas-Fort Worth-Arlington, TX","Dallas-Fort Worth-Arlington, TX",100
168,"Providence-Warwick, RI-MA","Providence-Warwick, RI-MA",100
340,"Richmond, VA","Richmond, VA",100
165,"Baltimore-Columbia-Towson, MD","Baltimore-Columbia-Towson, MD",100
142,"Kansas City, MO-KS","Kansas City, MO-KS",100
32,"Tucson, AZ","Tucson, AZ",100
35,"Memphis, TN-MS-AR","Memphis, TN-MS-AR",100
46,"Fresno, CA","Fresno, CA",100
53,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",100
58,"Riverside-San Bernardino-Ontario, CA","Riverside-San Bernardino-Ontario, CA",100
63,"San Jose-Sunnyvale-Santa Clara, CA","San Jose-Sunnyvale-Santa Clara, CA",100
79,"Hartford-West Hartford-East Hartford, CT","Hartford-West Hartford-East Hartford, CT",100
83,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD","Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",100
85,"Washington-Arlington-Alexandria, DC-VA-MD-WV","Washington-Arlington-Alexandria, DC-VA-MD-WV",100
87,"Miami-Fort Lauderdale-West Palm Beach, FL","Miami-Fort Lauderdale-West Palm Beach, FL",100
89,"Jacksonville, FL","Jacksonville, FL",100
91,"Tampa-St. Petersburg-Clearwater, FL","Tampa-St. Petersburg-Clearwater, FL",100
96,"Orlando-Kissimmee-Sanford, FL","Orlando-Kissimmee-Sanford, FL",100
103,"Atlanta-Sandy Springs-Roswell, GA","Atlanta-Sandy Springs-Roswell, GA",100
109,"Urban Honolulu, HI","Urban Honolulu, HI",100
116,"St. Louis, MO-IL","St. Louis, MO-IL",100
122,"Louisville/Jefferson County, KY-IN","Louisville/Jefferson County, KY-IN",100
147,"Cincinnati, OH-KY-IN","Cincinnati, OH-KY-IN",100
346,"Seattle-Tacoma-Bellevue, WA","Seattle-Tacoma-Bellevue, WA",100

In [204]:
matches_df['CBSA Name'] = matches_df['cbsa_name']

In [205]:
metros['CBSA Name'] = metros['matched_metro_area_2023']

In [206]:
matches_df_merged = matches_df.merge(metros, on='CBSA Name', how='left')

In [207]:
matches_df_merged

,cbsa_name,matched_metro,score,CBSA Name,metro_area_2010,population_2014,matched_metro_area_2023,match_score,population_2023,pop_pct_change
0,"Chicago-Naperville-Elgin, IL-IN-WI","Chicago-Naperville-Elgin, IL-IN",95,"Chicago-Naperville-Elgin, IL-IN-WI",NaN,NaN,NaN,NaN,NaN,NaN
1,"Salt Lake City, UT","Salt Lake City-Murray, UT",95,"Salt Lake City, UT",NaN,NaN,NaN,NaN,NaN,NaN
2,"Grand Rapids-Wyoming, MI","Grand Rapids-Wyoming-Kentwood, MI",95,"Grand Rapids-Wyoming, MI",NaN,NaN,NaN,NaN,NaN,NaN
3,"Raleigh, NC","Raleigh-Cary, NC",95,"Raleigh, NC",NaN,NaN,NaN,NaN,NaN,NaN
4,"New York-Newark-Jersey City, NY-NJ-PA","New York-Newark-Jersey City, NY-NJ",96,"New York-Newark-Jersey City, NY-NJ-PA",NaN,NaN,NaN,NaN,NaN,NaN
5,"Boston-Cambridge-Newton, MA-NH","Boston-Cambridge-Newton, MA-NH",100,"Boston-Cambridge-Newton, MA-NH","Boston-Cambridge-Newton, MA-NH",4650876.0,"Boston-Cambridge-Newton, MA-NH",100.0,4917661.0,0.057362
6,"Detroit-Warren-Dearborn, MI","Detroit-Warren-Dearborn, MI",100,"Detroit-Warren-Dearborn, MI","Detroit-Warren-Dearborn, MI",4292647.0,"Detroit-Warren-Dearborn, MI",100.0,4367620.0,0.017465
7,"Minneapolis-St. Paul-Bloomington, MN-WI","Minneapolis-St. Paul-Bloomington, MN-WI",100,"Minneapolis-St. Paul-Bloomington, MN-WI","Minneapolis-St. Paul-Bloomington, MN-WI",3424786.0,"Minneapolis-St. Paul-Bloomington, MN-WI",100.0,3693351.0,0.078418
8,"Rochester, NY","Rochester, NY",100,"Rochester, NY","Rochester, NY",1082578.0,"Rochester, NY",100.0,1058875.0,-0.021895
9,"Charlotte-Concord-Gastonia, NC-SC","Charlotte-Concord-Gastonia, NC-SC",100,"Charlotte-Concord-Gastonia, NC-SC","Charlotte-Concord-Gastonia, NC-SC",2298915.0,"Charlotte-Concord-Gastonia, NC-SC",100.0,2712818.0,0.180043
10,"Columbus, OH","Columbus, OH",100,"Columbus, OH","Columbus, OH",1948188.0,"Columbus, OH",100.0,2151847.0,0.104538
11,"Oklahoma City, OK","Oklahoma City, OK",100,"Oklahoma City, OK","Oklahoma City, OK",1297998.0,"Oklahoma City, OK",100.0,1445122.0,0.113347
12,"Tulsa, OK","Tulsa, OK",100,"Tulsa, OK","Tulsa, OK",954055.0,"Tulsa, OK",100.0,1026209.0,0.075629
13,"Portland-Vancouver-Hillsboro, OR-WA","Portland-Vancouver-Hillsboro, OR-WA",100,"Portland-Vancouver-Hillsboro, OR-WA","Portland-Vancouver-Hillsboro, OR-WA",2288796.0,"Portland-Vancouver-Hillsboro, OR-WA",100.0,2510529.0,0.096878
14,"Pittsburgh, PA","Pittsburgh, PA",100,"Pittsburgh, PA","Pittsburgh, PA",2358793.0,"Pittsburgh, PA",100.0,2443921.0,0.036090
15,"Nashville-Davidson--Murfreesboro--Franklin, TN","Nashville-Davidson--Murfreesboro--Franklin, TN",100,"Nashville-Davidson--Murfreesboro--Franklin, TN","Nashville-Davidson--Murfreesboro--Franklin, TN",1730515.0,"Nashville-Davidson--Murfreesboro--Franklin, TN",100.0,2043713.0,0.180985
16,"San Antonio-New Braunfels, TX","San Antonio-New Braunfels, TX",100,"San Antonio-New Braunfels, TX","San Antonio-New Braunfels, TX",2239222.0,"San Antonio-New Braunfels, TX",100.0,2612802.0,0.166835
17,"Dallas-Fort Worth-Arlington, TX","Dallas-Fort Worth-Arlington, TX",100,"Dallas-Fort Worth-Arlington, TX","Dallas-Fort Worth-Arlington, TX",6703020.0,"Dallas-Fort Worth-Arlington, TX",100.0,7807555.0,0.164782
18,"Providence-Warwick, RI-MA","Providence-Warwick, RI-MA",100,"Providence-Warwick, RI-MA","Providence-Warwick, RI-MA",1604317.0,"Providence-Warwick, RI-MA",100.0,1673807.0,0.043314
19,"Richmond, VA","Richmond, VA",100,"Richmond, VA","Richmond, VA",1234058.0,"Richmond, VA",100.0,1327321.0,0.075574
20,"Baltimore-Columbia-Towson, MD","Baltimore-Columbia-Towson, MD",100,"Baltimore-Columbia-Towson, MD","Baltimore-Columbia-Towson, MD",2753396.0,"Baltimore-Columbia-Towson, MD",100.0,2839409.0,0.031239
21,"Kansas City, MO-KS","Kansas City, MO-KS",100,"Kansas City, MO-KS","Kansas City, MO-KS",2040869.0,"Kansas City, MO-KS",100.0,2202006.0,0.078955
22,"Tucson, AZ","Tucson, AZ",100,"Tucson, AZ","Tucson, AZ",993144.0,"Tucson, AZ",100.0,1049947.0,0.057195
23,"Memphis, TN-MS-AR","Memphis, TN-MS-AR",100,"Memphis, TN-MS-AR","Memphis, TN-MS-AR",1337014.0,"Memphis, TN-MS-AR",100.0,1341606.0,0.003435
24,"Fresno, CA","Fresno, CA",100,"Fresno, CA","Fresno, CA",948844.0,"Fresno, CA",100.0,1170942.0,0.234072
25,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",100,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",13060534.0,"Los Angeles-Long Beach-Anaheim, CA",100.0,13012469.0,-0.003680
26,"Riverside-San Bernardino-Ontario, CA","Riverside-San Bernardino-Ontario, CA",100,"Riverside-San Bernardino-Ontario, CA","Riverside-San Bernardino-Ontario, CA",4345485.0,"Riverside-San Bernardino-Ontario, CA",100.0,4637725.0,0.067251
27,"San Jose-Sunnyvale-Santa Clara, CA","San Jose-Sunnyvale-Santa Clara, CA",100,"San Jose-Sunnyvale-Santa Clara, CA","San Jose-Sunnyvale-Santa Clara, CA",1898457.0,"San Jose-Sunnyvale-Santa Clara, CA",100.0,1969353.0,0.037344
28,"Hartford-West Hartford-East Hartford, CT","Hartford-West Hartford-East Hartford, CT",100,"Hartford-West Hartford-East Hartford, CT","Hartford-West Hartford-East Hartford, CT",1215159.0,"Hartford-West Hartford-East Hartford, CT",100.0,1144012.0,-0.058550
29,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD","Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",100,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD","Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",6015336.0,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",100.0,6241882.0,0.037661
30,"Washington-Arlington-Alexandria, DC-VA-MD-WV","Washington-Arlington-Alexandria, DC-VA-MD-WV",100,"Washington-Arlington-Alexandria, DC-VA-MD-WV","Washington-Arlington-Alexandria, DC-VA-MD-WV",5863608.0,"Washington-Arlington-Alexandria, DC-VA-MD-WV",100.0,6263796.0,0.068249
31,"Miami-Fort Lauderdale-West Palm Beach, FL","Miami-Fort Lauderdale-West Palm Beach, FL",100,"Miami-Fort Lauderdale-West Palm Beach, FL","Miami-Fort Lauderdale-West Palm Beach, FL",5775204.0,"Miami-Fort Lauderdale-West Palm Beach, FL",100.0,6138876.0,0.062971
32,"Jacksonville, FL","Jacksonville, FL",100,"Jacksonville, FL","Jacksonville, FL",1380995.0,"Jacksonville, FL",100.0,1645707.0,0.191682
33,"Tampa-St. Petersburg-Clearwater, FL","Tampa-St. Petersburg-Clearwater, FL",100,"Tampa-St. Petersburg-Clearwater, FL","Tampa-St. Petersburg-Clearwater, FL",2851235.0,"Tampa-St. Petersburg-Clearwater, FL",100.0,3240469.0,0.136514
34,"Orlando-Kissimmee-Sanford, FL","Orlando-Kissimmee-Sanford, FL",100,"Orlando-Kissimmee-Sanford, FL","Orlando-Kissimmee-Sanford, FL",2226835.0,"Orlando-Kissimmee-Sanford, FL",100.0,2721022.0,0.221923
35,"Atlanta-Sandy Springs-Roswell, GA","Atlanta-Sandy Springs-Roswell, GA",100,"Atlanta-Sandy Springs-Roswell, GA","Atlanta-Sandy Springs-Roswell, GA",5455053.0,"Atlanta-Sandy Springs-Roswell, GA",100.0,6176937.0,0.132333
36,"Urban Honolulu, HI","Urban Honolulu, HI",100,"Urban Honolulu, HI","Urban Honolulu, HI",975690.0,"Urban Honolulu, HI",100.0,1003666.0,0.028673
37,"St. Louis, MO-IL","St. Louis, MO-IL",100,"St. Louis, MO-IL","St. Louis, MO-IL",2797737.0,"St. Louis, MO-IL",100.0,2809414.0,0.004174
38,"Louisville/Jefferson County, KY-IN","Louisville/Jefferson County, KY-IN",100,"Louisville/Jefferson County, KY-IN","Louisville/Jefferson County, KY-IN",1253305.0,"Louisville/Jefferson County, KY-IN",100.0,1361847.0,0.086605
39,"Cincinnati, OH-KY-IN","Cincinnati, OH-KY-IN",100,"Cincinnati, OH-KY-IN","Cincinnati, OH-KY-IN",2131793.0,"Cincinnati, OH-KY-IN",100.0,2255257.0,0.057916
40,"Seattle-Tacoma-Bellevue, WA","Seattle-Tacoma-Bellevue, WA",100,"Seattle-Tacoma-Bellevue, WA","Seattle-Tacoma-Bellevue, WA",3557037.0,"Seattle-Tacoma-Bellevue, WA",100.0,4021467.0,0.130567

## Filtering the air quality dataset only to metropolitan areas listed in the metros data

In [243]:
# First, extract the list of matched metro names from your matches_df
matched_metros = matches_df['cbsa_name'].unique()

# Now filter all_years_df using that list
filtered_df = all_years_df[all_years_df['CBSA Name'].isin(matched_metros)]

In [209]:
filtered_df.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,Year
0,55,59,19,88101,1,42.50472,-87.8093,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-04-28,Micrograms/cubic meter (LC),NaN,1,100.0,27.0,27.0,0,84.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,CHIWAUKEE PRAIRIE STATELINE,"CHIWAUKEE PRAIRIE, 11838 FIRST COURT",Wisconsin,Kenosha,Pleasant Prairie,"Chicago-Naperville-Elgin, IL-IN-WI",2024-05-19,1997
1,55,59,19,88101,1,42.50472,-87.8093,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-05-10,Micrograms/cubic meter (LC),NaN,1,100.0,8.0,8.0,0,44.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,CHIWAUKEE PRAIRIE STATELINE,"CHIWAUKEE PRAIRIE, 11838 FIRST COURT",Wisconsin,Kenosha,Pleasant Prairie,"Chicago-Naperville-Elgin, IL-IN-WI",2024-05-19,1997
2,55,59,19,88101,1,42.50472,-87.8093,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-05-16,Micrograms/cubic meter (LC),NaN,1,100.0,6.0,6.0,0,33.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,CHIWAUKEE PRAIRIE STATELINE,"CHIWAUKEE PRAIRIE, 11838 FIRST COURT",Wisconsin,Kenosha,Pleasant Prairie,"Chicago-Naperville-Elgin, IL-IN-WI",2024-05-19,1997
3,55,59,19,88101,1,42.50472,-87.8093,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-05-22,Micrograms/cubic meter (LC),NaN,1,100.0,6.0,6.0,0,33.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,CHIWAUKEE PRAIRIE STATELINE,"CHIWAUKEE PRAIRIE, 11838 FIRST COURT",Wisconsin,Kenosha,Pleasant Prairie,"Chicago-Naperville-Elgin, IL-IN-WI",2024-05-19,1997
4,55,59,19,88101,1,42.50472,-87.8093,WGS84,PM2.5 - Local Conditions,24 HOUR,PM25 24-hour 2012,1997-05-28,Micrograms/cubic meter (LC),NaN,1,100.0,11.0,11.0,0,55.0,117,R & P Model 2000 PM2.5 Sampler w/WINS - GRAVIM...,CHIWAUKEE PRAIRIE STATELINE,"CHIWAUKEE PRAIRIE, 11838 FIRST COURT",Wisconsin,Kenosha,Pleasant Prairie,"Chicago-Naperville-Elgin, IL-IN-WI",2024-05-19,1997

In [210]:
filtered_df.shape

(2994204, 30)

## Filtering by 24-HOUR readings and averaging the Air Quality Index for all local sites within the same metro area per year

In [211]:
readings_24_hr = filtered_df[filtered_df['Sample Duration'] == '24 HOUR']

In [212]:
readings_24_hr['CBSA Name'].value_counts().shape

(41,)

In [213]:
site_year_avg = readings_24_hr.groupby(['Local Site Name', 'Year'], as_index=False)['AQI'].mean()

In [214]:
site_year_avg

                                        Local Site Name  Year        AQI
0                                         Davidsonville  1999  53.761905
1                                         Davidsonville  2000  55.525000
2                                         Davidsonville  2001  53.518519
3                                         Davidsonville  2002  53.860870
4                                         Davidsonville  2003  49.509804
...                                                 ...   ...        ...
6410                               Yorkville, King Farm  2017  29.727273
6411  inactive military resv 680 hudson rd sudbury m...  1999  44.421053
6412  inactive military resv 680 hudson rd sudbury m...  2000  43.027397
6413  inactive military resv 680 hudson rd sudbury m...  2001  48.078652
6414  inactive military resv 680 hudson rd sudbury m...  2002  44.753846

[6415 rows x 3 columns]

In [215]:
site_to_cbsa = readings_24_hr[['Local Site Name', 'CBSA Name']].drop_duplicates()

In [216]:
site_year_avg = site_year_avg.merge(site_to_cbsa, on='Local Site Name', how='left')

In [217]:
site_year_avg

,Local Site Name,Year,AQI,CBSA Name
0,Davidsonville,1999,53.761905,"Baltimore-Columbia-Towson, MD"
1,Davidsonville,2000,55.525000,"Baltimore-Columbia-Towson, MD"
2,Davidsonville,2001,53.518519,"Baltimore-Columbia-Towson, MD"
3,Davidsonville,2002,53.860870,"Baltimore-Columbia-Towson, MD"
4,Davidsonville,2003,49.509804,"Baltimore-Columbia-Towson, MD"
...,...,...,...,...
6497,"Yorkville, King Farm",2017,29.727273,"Atlanta-Sandy Springs-Roswell, GA"
6498,inactive military resv 680 hudson rd sudbury m...,1999,44.421053,"Boston-Cambridge-Newton, MA-NH"
6499,inactive military resv 680 hudson rd sudbury m...,2000,43.027397,"Boston-Cambridge-Newton, MA-NH"
6500,inactive military resv 680 hudson rd sudbury m...,2001,48.078652,"Boston-Cambridge-Newton, MA-NH"
6501,inactive military resv 680 hudson rd sudbury m...,2002,44.753846,"Boston-Cambridge-Newton, MA-NH"

In [218]:
cbsa_year_avg = site_year_avg.groupby(['CBSA Name', 'Year'], as_index=False)['AQI'].mean()

In [219]:
cbsa_year_avg.head(30)

                            CBSA Name  Year        AQI
0   Atlanta-Sandy Springs-Roswell, GA  1999  71.971945
1   Atlanta-Sandy Springs-Roswell, GA  2000  68.526673
2   Atlanta-Sandy Springs-Roswell, GA  2001  64.358809
3   Atlanta-Sandy Springs-Roswell, GA  2002  61.345567
4   Atlanta-Sandy Springs-Roswell, GA  2003  61.938421
5   Atlanta-Sandy Springs-Roswell, GA  2004  62.294681
6   Atlanta-Sandy Springs-Roswell, GA  2005  62.427995
7   Atlanta-Sandy Springs-Roswell, GA  2006  61.672589
8   Atlanta-Sandy Springs-Roswell, GA  2007  60.788780
9   Atlanta-Sandy Springs-Roswell, GA  2008  54.219355
10  Atlanta-Sandy Springs-Roswell, GA  2009  51.015677
11  Atlanta-Sandy Springs-Roswell, GA  2010  55.026908
12  Atlanta-Sandy Springs-Roswell, GA  2011  52.448513
13  Atlanta-Sandy Springs-Roswell, GA  2012  48.743033
14  Atlanta-Sandy Springs-Roswell, GA  2013  45.828205
15  Atlanta-Sandy Springs-Roswell, GA  2014  48.163173
16  Atlanta-Sandy Springs-Roswell, GA  2015  44.887319
17  Atlanta-Sandy Springs-Roswell, GA  2016  44.904901
18  Atlanta-Sandy Springs-Roswell, GA  2017  43.214218
19  Atlanta-Sandy Springs-Roswell, GA  2018  41.567224
20  Atlanta-Sandy Springs-Roswell, GA  2019  44.170674
21  Atlanta-Sandy Springs-Roswell, GA  2020  41.661393
22  Atlanta-Sandy Springs-Roswell, GA  2021  44.387061
23  Atlanta-Sandy Springs-Roswell, GA  2022  41.616496
24  Atlanta-Sandy Springs-Roswell, GA  2023  47.210780
25  Atlanta-Sandy Springs-Roswell, GA  2024  40.707072
26      Baltimore-Columbia-Towson, MD  1999  62.824925
27      Baltimore-Columbia-Towson, MD  2000  61.402066
28      Baltimore-Columbia-Towson, MD  2001  60.354261
29      Baltimore-Columbia-Towson, MD  2002  59.129313

In [220]:
pivot_df = cbsa_year_avg.pivot(index='CBSA Name', columns='Year', values='AQI')

In [221]:
pivot_df = pivot_df.reset_index()

In [222]:
pivot_df

Year,CBSA Name,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"Atlanta-Sandy Springs-Roswell, GA",NaN,NaN,71.971945,68.526673,64.358809,61.345567,61.938421,62.294681,62.427995,61.672589,60.788780,54.219355,51.015677,55.026908,52.448513,48.743033,45.828205,48.163173,44.887319,44.904901,43.214218,41.567224,44.170674,41.661393,44.387061,41.616496,47.210780,40.707072
1,"Baltimore-Columbia-Towson, MD",NaN,NaN,62.824925,61.402066,60.354261,59.129313,57.382264,58.145234,59.499710,55.584224,56.180278,54.016698,48.428399,47.844782,47.295553,46.067550,43.458322,43.787059,44.306648,40.857023,38.760179,37.504124,39.591275,33.790063,39.098485,34.339441,44.005513,34.086339
2,"Boston-Cambridge-Newton, MA-NH",NaN,NaN,53.015121,51.274769,53.423984,49.144801,48.301866,49.376003,48.274410,42.652092,45.103263,45.955534,41.835347,39.752198,40.036540,40.101608,36.835646,31.199469,32.055512,30.612476,29.394419,28.135560,26.741901,35.515335,40.599395,31.603171,37.192751,31.168128
3,"Charlotte-Concord-Gastonia, NC-SC",NaN,NaN,61.263745,62.805688,58.738356,58.356246,57.665661,58.858567,59.905740,58.503773,56.745160,54.760923,48.452519,51.406007,48.371246,45.277453,43.778014,44.218848,41.784050,43.760548,42.299931,39.987182,42.442514,39.366375,42.891730,41.174138,45.967057,36.855556
4,"Chicago-Naperville-Elgin, IL-IN-WI",57.121951,64.817948,61.906111,61.029117,61.541239,59.300711,58.109288,55.064670,60.733486,54.565680,57.362744,50.786457,49.275134,51.518536,50.429847,48.988311,48.564876,47.810368,46.145483,42.426197,41.608099,45.248039,43.272777,43.787079,45.135499,44.089014,47.185000,38.336416
5,"Cincinnati, OH-KY-IN",NaN,NaN,66.045610,66.429202,62.431134,62.300452,61.640908,59.329370,65.330448,57.522166,60.286881,56.333505,54.601768,56.227249,52.621895,51.371128,50.187294,50.463269,47.397648,45.948778,43.543902,44.754969,45.461036,43.027051,45.052552,42.153787,46.260528,41.889259
6,"Columbus, OH",NaN,NaN,65.973679,65.645011,64.536280,62.513925,61.620498,58.492328,61.464032,54.985002,57.889854,53.072319,50.437011,53.681544,50.854804,49.302735,47.399805,46.859915,46.816192,42.088701,41.472587,43.032253,43.655614,41.975704,44.300506,40.263206,44.808330,38.244466
7,"Dallas-Fort Worth-Arlington, TX",NaN,NaN,55.182665,55.069324,54.474683,53.819476,54.755092,53.056432,55.054705,50.612061,52.077191,49.689446,46.353624,47.832944,49.860525,48.958440,46.389586,47.371336,45.401910,41.800846,43.916453,43.237846,41.089705,42.275868,43.942400,43.240376,44.152778,43.941176
8,"Detroit-Warren-Dearborn, MI",NaN,NaN,59.202340,60.974083,61.262894,60.058202,60.204629,58.324330,60.539365,53.755833,54.485865,50.023950,46.036424,43.947819,44.440858,46.000165,43.162480,45.802065,45.004383,41.982959,40.880553,42.244864,40.573002,37.569095,42.449735,39.207912,44.791150,38.160211
9,"Fresno, CA",NaN,NaN,76.200502,71.539332,70.661060,72.401381,69.144136,65.473344,64.623546,66.296420,66.026657,63.500509,56.554523,55.415311,58.957581,70.434040,61.414957,55.028686,55.228127,51.851587,56.136841,60.806685,47.905269,65.485126,62.922078,54.940000,49.528455,42.590361
10,"Grand Rapids-Wyoming, MI",NaN,NaN,54.310767,54.461693,56.273138,54.852248,54.199199,49.167356,55.227965,51.796298,51.654794,47.892309,45.244669,43.207971,43.167753,43.695348,40.988218,45.033416,44.334227,41.028604,41.854304,40.226608,38.564555,37.553842,38.305263,35.684211,41.365385,29.826087
11,"Hartford-West Hartford-East Hartford, CT",NaN,NaN,47.772321,47.238255,51.399381,50.013559,50.573964,48.032738,49.487179,46.089231,44.478754,46.870080,40.864988,38.408042,42.847394,38.868874,38.522847,38.185724,40.932065,35.535394,33.816686,33.891371,29.815055,32.719298,35.180328,31.631579,36.700000,28.193548
12,"Jacksonville, FL",NaN,NaN,53.388784,53.326779,50.479710,45.976707,46.619451,49.433205,47.685469,46.955565,46.512835,43.974133,40.558651,43.180302,NaN,38.210476,34.959461,38.840961,37.636329,38.544950,37.992520,37.381577,35.848995,35.511111,34.764286,38.019868,NaN,NaN
13,"Kansas City, MO-KS",NaN,NaN,54.360971,53.025627,53.839762,53.733197,53.135034,51.615406,53.670732,50.087858,50.855896,49.053256,46.371710,47.857122,46.853209,44.371389,42.750521,44.918913,42.507790,39.971202,45.829713,45.216750,42.323743,39.052937,45.691273,43.955002,47.914721,40.101124
14,"Los Angeles-Long Beach-Anaheim, CA",NaN,NaN,72.399439,68.359661,69.317498,69.013847,65.299108,62.783797,60.427711,56.959251,57.974208,55.071509,53.689529,48.538945,49.902546,48.388306,50.611558,54.210913,48.063064,48.146789,50.333665,50.932957,45.918922,53.079805,51.674487,49.678424,47.737663,44.718164
15,"Louisville/Jefferson County, KY-IN",NaN,NaN,62.229327,64.179449,64.263861,62.076460,61.151728,57.788092,64.356408,58.462646,60.938260,56.023097,53.083512,56.841523,52.069857,49.434306,48.828518,50.162578,45.696597,42.517389,41.433509,43.727356,42.497176,41.436097,43.967947,41.795408,45.173554,39.852778
16,"Memphis, TN-MS-AR",NaN,NaN,61.513343,58.817803,54.658592,54.053019,54.205813,52.998757,56.762728,54.849495,54.293949,52.534662,47.421383,50.831780,49.987681,47.622951,45.399114,44.202786,42.414804,40.490986,41.747774,42.163459,41.587417,39.047051,40.546573,41.336095,44.609903,41.997235
17,"Miami-Fort Lauderdale-West Palm Beach, FL",NaN,NaN,46.092052,46.638670,39.636587,40.332215,40.143955,42.233755,42.127480,40.157515,38.186711,36.094528,33.736769,36.243615,NaN,36.425673,32.995323,33.028562,31.694569,35.388122,37.485163,35.598526,33.769057,34.840954,36.790880,34.493470,37.815368,39.899058
18,"Minneapolis-St. Paul-Bloomington, MN-WI",NaN,NaN,46.187987,50.160010,47.870981,46.669032,45.342047,40.761473,45.293105,43.648130,44.612075,45.463257,42.966361,42.828372,41.475320,43.002274,42.366958,41.438823,36.333521,33.050869,34.399530,38.805773,36.289994,37.808005,41.172283,34.660547,43.331048,31.473695
19,"Nashville-Davidson--Murfreesboro--Franklin, TN",NaN,NaN,64.787314,62.105622,57.143387,54.774269,57.878345,54.746164,58.529527,56.888914,55.538045,NaN,NaN,NaN,NaN,NaN,44.588217,46.195829,42.567112,41.015912,40.221338,41.411011,40.250174,43.647268,41.563307,40.636475,45.655524,37.122679
20,"New York-Newark-Jersey City, NY-NJ-PA",NaN,NaN,57.063061,57.740361,56.302782,55.604058,55.357104,53.322619,57.106314,50.871693,53.594410,51.796663,44.927129,43.533207,46.032854,44.664274,42.372420,43.150256,42.682005,39.181181,38.691812,38.899645,37.448864,37.652707,38.965385,36.004929,41.138967,32.578617
21,"Oklahoma City, OK",NaN,NaN,45.696609,47.889185,46.411991,44.826033,47.096464,44.833847,47.678719,43.460973,50.745984,48.987706,44.711389,44.877828,46.806510,46.458141,43.891956,43.153623,40.401052,38.536694,38.541400,42.713102,36.789323,36.445709,42.975743,38.656206,41.265044,38.982163
22,"Orlando-Kissimmee-Sanford, FL",NaN,NaN,50.541390,51.948454,48.727205,45.199060,45.395543,48.017096,46.500218,45.188591,43.633136,39.444137,37.714006,39.963019,NaN,36.402783,32.533588,34.183935,31.989924,34.541523,34.166667,33.888889,30.900000,31.032258,31.730769,36.500000,38.607143,36.466667
23,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NaN,NaN,56.266134,59.108705,59.042865,57.525469,57.064044,54.791619,57.277661,53.200035,54.868873,53.759419,47.964220,45.748218,46.598614,45.415311,44.767048,45.039646,43.674674,40.490269,39.413405,37.624584,37.475346,37.118793,39.829445,35.627998,41.822321,34.208422
24,"Pittsburgh, PA",NaN,NaN,62.613115,60.804772,62.694098,59.649530,59.477979,59.694072,62.271141,57.155039,59.585515,55.715228,52.135186,53.408779,50.090263,48.569181,46.596011,46.955749,46.280768,44.855678,46.723997,44.329551,43.118617,39.453172,44.183065,40.386488,44.100491,36.342984
25,"Portland-Vancouver-Hillsboro, OR-WA",NaN,NaN,41.090617,42.211747,39.349114,39.093654,38.043604,40.385790,43.450596,45.839286,36.892684,39.574001,38.922110,31.615244,37.325161,35.251928,42.893114,33.158333,36.750597,30.927178,36.842140,36.203977,34.309197,37.403968,32.677297,36.587015,30.756885,23.263158
26,"Providence-Warwick, RI-MA",NaN,NaN,45.407378,45.948907,48.840815,45.416636,48.004742,47.654191,47.557702,43.055480,44.110866,44.091661,39.341667,38.075224,40.893115,38.907300,37.089001,33.052526,33.931611,31.190670,29.676134,29.190393,29.317614,39.938636,44.742932,32.713690,37.072787,28.126572
27,"Raleigh, NC",NaN,NaN,61.634069,62.326733,58.394299,57.104369,57.175309,55.784062,55.655405,56.510965,55.622449,50.564548,44.174510,47.679166,45.243272,41.815134,40.462318,42.750650,38.527836,40.100102,39.989481,38.893443,40.537037,31.292683,40.280702,36.950000,42.743119,36.711864
28,"Richmond, VA",NaN,NaN,58.096372,59.391293,56.316706,56.169980,55.260047,54.485760,56.459481,53.946197,53.192821,49.199304,44.242063,46.399684,44.159186,42.589408,40.526094,41.625130,39.954883,38.549921,38.514686,36.420298,36.921052,32.053438,37.899686,33.299929,39.994643,34.617449
29,"Riverside-San Bernardino-Ontario, CA",NaN,NaN,72.111018,67.188652,69.870665,68.919113,64.263961,60.974617,58.059435,58.845037,59.009586,52.756329,51.177454,46.188259,46.114775,46.725260,46.878672,47.971898,47.796375,44.988688,44.375066,46.887728,41.752087,45.396913,45.605328,42.868364,42.563151,42.404521
30,"Rochester, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.729167,51.281818,42.966387,43.361345,42.547826,38.085470,39.324324,42.021978,42.504854,36.170940,37.016667,38.873639,32.853258,34.727959,35.834030,33.671665,30.760940,35.087002,30.893964,38.236017,29.625000
31,"Salt Lake City, UT",NaN,NaN,44.391320,46.344841,47.380415,51.330618,43.181813,55.058707,46.657580,43.594702,47.647688,43.541771,42.116757,37.933094,34.919962,36.439303,43.327250,32.177345,38.580560,37.630675,37.594217,39.953970,32.717803,37.085921,41.140407,36.992201,33.759915,31.845290
32,"San Antonio-New Braunfels, TX",NaN,NaN,57.042857,47.311932,42.816224,44.294639,43.427294,NaN,NaN,NaN,NaN,43.183111,44.840414,43.667832,44.770569,42.666667,39.510558,43.166667,41.492589,40.204070,42.331393,39.546164,41.774194,41.903226,39.633333,42.193548,38.444444,53.444444
33,"San Jose-Sunnyvale-Santa Clara, CA",NaN,NaN,70.095029,60.921498,55.874278,58.161128,52.137928,53.460625,52.559583,48.733452,40.143707,43.193802,38.649917,44.155340,47.716102,43.531073,46.824000,44.563025,48.102564,41.178947,45.837838,48.592000,38.774194,48.235772,41.655738,44.641667,38.162393,NaN
34,"Seattle-Tacoma-Bellevue, WA",NaN,NaN,46.162445,49.313357,46.221545,43.382621,42.102766,40.341717,44.470690,41.777240,39.342152,39.400304,40.460030,32.567133,33.715500,35.738265,33.348455,31.628111,33.336066,31.786821,33.581325,34.327455,35.805186,34.413949,33.155237,32.750379,29.126954,29.004396
35,"St. Louis, MO-IL",NaN,NaN,63.363965,63.162146,60.783063,61.278575,58.883231,56.307124,62.496751,56.485199,58.452735,54.099829,51.365480,55.159257,53.191957,48.584951,50.063260,50.637724,47.554339,44.471235,44.331312,47.608503,46.296570,45.976563,45.861047,45.320369,46.761845,40.939175
36,"Tampa-St. Petersburg-Clearwater, FL",NaN,NaN,54.404464,54.488795,51.583593,49.908265,47.451932,50.129347,49.252028,46.966062,46.519886,42.309202,39.980627,43.303575,NaN,36.841426,34.171064,35.069116,36.560979,37.232415,39.821838,37.038542,36.248677,39.659091,38.821429,38.789116,40.861314,40.114754
37,"Tucson, AZ",NaN,NaN,44.144951,38.717317,39.121875,34.183206,34.848685,31.092004,33.499627,31.693203,30.929293,30.173875,29.358919,27.885150,30.302089,30.929752,27.858861,32.787178,28.187500,33.161811,35.062031,32.233333,27.578431,32.801653,33.137931,32.663866,28.641026,29.988235
38,"Tulsa, OK",NaN,NaN,51.600791,50.089431,48.638270,45.207262,47.299745,48.475885,52.647230,49.479429,53.558404,51.972191,49.363749,50.815812,50.376404,46.698068,44.461353,43.622951,41.110482,39.575581,39.096591,40.729885,36.441341,35.211111,38.878788,39.000000,42.587209,39.815217
39,"Urban Honolulu, HI",NaN,NaN,24.142399,22.755795,24.207283,23.000198,24.238941,21.292307,23.191221,21.807081,21.912940,26.357724,26.744444,19.740741,18.721739,20.754386,19.921739,NaN,NaN,NaN,NaN,24.009524,19.943925,19.818116,17.208333,21.404520,19.264921,19.491071
40,"Washington-Arlington-Alexandria, DC-VA-MD-WV",NaN,NaN,57.976664,59.689804,58.838144,58.183780,55.326038,55.298357,57.750099,53.381486,54.735026,51.910036,46.188450,47.594307,45.646976,44.316919,42.204747,42.768215,42.901663,38.775045,38.139825,37.972033,37.056526,31.953383,40.043225,35.515838,38.285050,32.813553

In [223]:
metros

,metro_area_2010,population_2014,matched_metro_area_2023,match_score,population_2023,pop_pct_change,CBSA Name
0,"Austin-Round Rock, TX",1835016,"Austin-Round Rock-San Marcos, TX",75.471698,2357497,0.284728,"Austin-Round Rock-San Marcos, TX"
1,"Fresno, CA",948844,"Fresno, CA",100.000000,1170942,0.234072,"Fresno, CA"
2,"Orlando-Kissimmee-Sanford, FL",2226835,"Orlando-Kissimmee-Sanford, FL",100.000000,2721022,0.221923,"Orlando-Kissimmee-Sanford, FL"
3,"Raleigh, NC",1189579,"Raleigh-Cary, NC",81.481481,1449594,0.218577,"Raleigh-Cary, NC"
4,"Jacksonville, FL",1380995,"Jacksonville, FL",100.000000,1645707,0.191682,"Jacksonville, FL"
5,"Nashville-Davidson--Murfreesboro--Franklin, TN",1730515,"Nashville-Davidson--Murfreesboro--Franklin, TN",100.000000,2043713,0.180985,"Nashville-Davidson--Murfreesboro--Franklin, TN"
6,"Charlotte-Concord-Gastonia, NC-SC",2298915,"Charlotte-Concord-Gastonia, NC-SC",100.000000,2712818,0.180043,"Charlotte-Concord-Gastonia, NC-SC"
7,"Houston-The Woodlands-Sugar Land, TX",6204141,"Houston-Pasadena-The Woodlands, TX",68.571429,7274714,0.172558,"Houston-Pasadena-The Woodlands, TX"
8,"San Antonio-New Braunfels, TX",2239222,"San Antonio-New Braunfels, TX",100.000000,2612802,0.166835,"San Antonio-New Braunfels, TX"
9,"Dallas-Fort Worth-Arlington, TX",6703020,"Dallas-Fort Worth-Arlington, TX",100.000000,7807555,0.164782,"Dallas-Fort Worth-Arlington, TX"
10,"Grand Rapids-Wyoming, MI",1007329,"Grand Rapids-Wyoming-Kentwood, MI",84.210526,1154320,0.145922,"Grand Rapids-Wyoming-Kentwood, MI"
11,"Phoenix-Mesa-Scottsdale, AZ",4337542,"Phoenix-Mesa-Chandler, AZ",76.923077,4941206,0.139172,"Phoenix-Mesa-Chandler, AZ"
12,"Tampa-St. Petersburg-Clearwater, FL",2851235,"Tampa-St. Petersburg-Clearwater, FL",100.000000,3240469,0.136514,"Tampa-St. Petersburg-Clearwater, FL"
13,"Atlanta-Sandy Springs-Roswell, GA",5455053,"Atlanta-Sandy Springs-Roswell, GA",100.000000,6176937,0.132333,"Atlanta-Sandy Springs-Roswell, GA"
14,"Seattle-Tacoma-Bellevue, WA",3557037,"Seattle-Tacoma-Bellevue, WA",100.000000,4021467,0.130567,"Seattle-Tacoma-Bellevue, WA"
15,"Salt Lake City, UT",1123643,"Salt Lake City-Murray, UT",83.720930,1261337,0.122542,"Salt Lake City-Murray, UT"
16,"Oklahoma City, OK",1297998,"Oklahoma City, OK",100.000000,1445122,0.113347,"Oklahoma City, OK"
17,"Columbus, OH",1948188,"Columbus, OH",100.000000,2151847,0.104538,"Columbus, OH"
18,"Portland-Vancouver-Hillsboro, OR-WA",2288796,"Portland-Vancouver-Hillsboro, OR-WA",100.000000,2510529,0.096878,"Portland-Vancouver-Hillsboro, OR-WA"
19,"Sacramento--Roseville--Arden-Arcade, CA",2197422,"Sacramento-Roseville-Folsom, CA",71.428571,2406563,0.095176,"Sacramento-Roseville-Folsom, CA"
20,"Indianapolis-Carmel-Anderson, IN",1931182,"Indianapolis-Carmel-Greenwood, IN",80.000000,2106327,0.090693,"Indianapolis-Carmel-Greenwood, IN"
21,"Louisville/Jefferson County, KY-IN",1253305,"Louisville/Jefferson County, KY-IN",100.000000,1361847,0.086605,"Louisville/Jefferson County, KY-IN"
22,"Kansas City, MO-KS",2040869,"Kansas City, MO-KS",100.000000,2202006,0.078955,"Kansas City, MO-KS"
23,"Minneapolis-St. Paul-Bloomington, MN-WI",3424786,"Minneapolis-St. Paul-Bloomington, MN-WI",100.000000,3693351,0.078418,"Minneapolis-St. Paul-Bloomington, MN-WI"
24,"Tulsa, OK",954055,"Tulsa, OK",100.000000,1026209,0.075629,"Tulsa, OK"
25,"Richmond, VA",1234058,"Richmond, VA",100.000000,1327321,0.075574,"Richmond, VA"
26,"Washington-Arlington-Alexandria, DC-VA-MD-WV",5863608,"Washington-Arlington-Alexandria, DC-VA-MD-WV",100.000000,6263796,0.068249,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
27,"Riverside-San Bernardino-Ontario, CA",4345485,"Riverside-San Bernardino-Ontario, CA",100.000000,4637725,0.067251,"Riverside-San Bernardino-Ontario, CA"
28,"Miami-Fort Lauderdale-West Palm Beach, FL",5775204,"Miami-Fort Lauderdale-West Palm Beach, FL",100.000000,6138876,0.062971,"Miami-Fort Lauderdale-West Palm Beach, FL"
29,"Cincinnati, OH-KY-IN",2131793,"Cincinnati, OH-KY-IN",100.000000,2255257,0.057916,"Cincinnati, OH-KY-IN"
30,"Boston-Cambridge-Newton, MA-NH",4650876,"Boston-Cambridge-Newton, MA-NH",100.000000,4917661,0.057362,"Boston-Cambridge-Newton, MA-NH"
31,"Tucson, AZ",993144,"Tucson, AZ",100.000000,1049947,0.057195,"Tucson, AZ"
32,"Cleveland-Elyria, OH",2067490,"Cleveland, OH",78.787879,2171978,0.050539,"Cleveland, OH"
33,"Virginia Beach-Norfolk-Newport News, VA-NC",1697898,"Virginia Beach-Chesapeake-Norfolk, VA-NC",70.731707,1782590,0.049880,"Virginia Beach-Chesapeake-Norfolk, VA-NC"
34,"Providence-Warwick, RI-MA",1604317,"Providence-Warwick, RI-MA",100.000000,1673807,0.043314,"Providence-Warwick, RI-MA"
35,"San Francisco-Oakland-Hayward, CA",4466251,"San Francisco-Oakland-Fremont, CA",81.818182,4653593,0.041946,"San Francisco-Oakland-Fremont, CA"
36,"Birmingham-Hoover, AL",1135534,"Birmingham, AL",80.000000,1181432,0.040420,"Birmingham, AL"
37,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",6015336,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",100.000000,6241882,0.037661,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
38,"San Jose-Sunnyvale-Santa Clara, CA",1898457,"San Jose-Sunnyvale-Santa Clara, CA",100.000000,1969353,0.037344,"San Jose-Sunnyvale-Santa Clara, CA"
39,"Pittsburgh, PA",2358793,"Pittsburgh, PA",100.000000,2443921,0.036090,"Pittsburgh, PA"
40,"Baltimore-Columbia-Towson, MD",2753396,"Baltimore-Columbia-Towson, MD",100.000000,2839409,0.031239,"Baltimore-Columbia-Towson, MD"
41,"Urban Honolulu, HI",975690,"Urban Honolulu, HI",100.000000,1003666,0.028673,"Urban Honolulu, HI"
42,"Buffalo-Cheektowaga-Niagara Falls, NY",1135667,"Buffalo-Cheektowaga, NY",76.666667,1161385,0.022646,"Buffalo-Cheektowaga, NY"
43,"Detroit-Warren-Dearborn, MI",4292647,"Detroit-Warren-Dearborn, MI",100.000000,4367620,0.017465,"Detroit-Warren-Dearborn, MI"
44,"St. Louis, MO-IL",2797737,"St. Louis, MO-IL",100.000000,2809414,0.004174,"St. Louis, MO-IL"
45,"Memphis, TN-MS-AR",1337014,"Memphis, TN-MS-AR",100.000000,1341606,0.003435,"Memphis, TN-MS-AR"
46,"Milwaukee-Waukesha-West Allis, WI",1565368,"Milwaukee-Waukesha, WI",76.363636,1566361,0.000634,"Milwaukee-Waukesha, WI"
47,"Los Angeles-Long Beach-Anaheim, CA",13060534,"Los Angeles-Long Beach-Anaheim, CA",100.000000,13012469,-0.003680,"Los Angeles-Long Beach-Anaheim, CA"
48,"New York-Newark-Jersey City, NY-NJ-PA",19865045,"New York-Newark-Jersey City, NY-NJ",95.774648,19756722,-0.005453,"New York-Newark-Jersey City, NY-NJ"
49,"Chicago-Naperville-Elgin, IL-IN-WI",9516448,"Chicago-Naperville-Elgin, IL-IN",95.384615,9359555,-0.016487,"Chicago-Naperville-Elgin, IL-IN"
50,"Rochester, NY",1082578,"Rochester, NY",100.000000,1058875,-0.021895,"Rochester, NY"
51,"Hartford-West Hartford-East Hartford, CT",1215159,"Hartford-West Hartford-East Hartford, CT",100.000000,1144012,-0.058550,"Hartford-West Hartford-East Hartford, CT"
52,"San Juan-Carolina-Caguas, PR",2297987,"San Juan-Bayamón-Caguas, PR",80.000000,2063795,-0.101912,"San Juan-Bayamón-Caguas, PR"

## Merging in the population percent change column

In [224]:
pop_pct_change = metros[['CBSA Name','pop_pct_change']]

In [225]:
pop_pct_change

                                         CBSA Name  pop_pct_change
0                 Austin-Round Rock-San Marcos, TX        0.284728
1                                       Fresno, CA        0.234072
2                    Orlando-Kissimmee-Sanford, FL        0.221923
3                                 Raleigh-Cary, NC        0.218577
4                                 Jacksonville, FL        0.191682
5   Nashville-Davidson--Murfreesboro--Franklin, TN        0.180985
6                Charlotte-Concord-Gastonia, NC-SC        0.180043
7               Houston-Pasadena-The Woodlands, TX        0.172558
8                    San Antonio-New Braunfels, TX        0.166835
9                  Dallas-Fort Worth-Arlington, TX        0.164782
10               Grand Rapids-Wyoming-Kentwood, MI        0.145922
11                       Phoenix-Mesa-Chandler, AZ        0.139172
12             Tampa-St. Petersburg-Clearwater, FL        0.136514
13               Atlanta-Sandy Springs-Roswell, GA        0.132333
14                     Seattle-Tacoma-Bellevue, WA        0.130567
15                       Salt Lake City-Murray, UT        0.122542
16                               Oklahoma City, OK        0.113347
17                                    Columbus, OH        0.104538
18             Portland-Vancouver-Hillsboro, OR-WA        0.096878
19                 Sacramento-Roseville-Folsom, CA        0.095176
20               Indianapolis-Carmel-Greenwood, IN        0.090693
21              Louisville/Jefferson County, KY-IN        0.086605
22                              Kansas City, MO-KS        0.078955
23         Minneapolis-St. Paul-Bloomington, MN-WI        0.078418
24                                       Tulsa, OK        0.075629
25                                    Richmond, VA        0.075574
26    Washington-Arlington-Alexandria, DC-VA-MD-WV        0.068249
27            Riverside-San Bernardino-Ontario, CA        0.067251
28       Miami-Fort Lauderdale-West Palm Beach, FL        0.062971
29                            Cincinnati, OH-KY-IN        0.057916
30                  Boston-Cambridge-Newton, MA-NH        0.057362
31                                      Tucson, AZ        0.057195
32                                   Cleveland, OH        0.050539
33        Virginia Beach-Chesapeake-Norfolk, VA-NC        0.049880
34                       Providence-Warwick, RI-MA        0.043314
35               San Francisco-Oakland-Fremont, CA        0.041946
36                                  Birmingham, AL        0.040420
37     Philadelphia-Camden-Wilmington, PA-NJ-DE-MD        0.037661
38              San Jose-Sunnyvale-Santa Clara, CA        0.037344
39                                  Pittsburgh, PA        0.036090
40                   Baltimore-Columbia-Towson, MD        0.031239
41                              Urban Honolulu, HI        0.028673
42                         Buffalo-Cheektowaga, NY        0.022646
43                     Detroit-Warren-Dearborn, MI        0.017465
44                                St. Louis, MO-IL        0.004174
45                               Memphis, TN-MS-AR        0.003435
46                          Milwaukee-Waukesha, WI        0.000634
47              Los Angeles-Long Beach-Anaheim, CA       -0.003680
48              New York-Newark-Jersey City, NY-NJ       -0.005453
49                 Chicago-Naperville-Elgin, IL-IN       -0.016487
50                                   Rochester, NY       -0.021895
51        Hartford-West Hartford-East Hartford, CT       -0.058550
52                     San Juan-Bayamón-Caguas, PR       -0.101912

In [226]:
merge = pivot_df.merge(pop_pct_change, on='CBSA Name', how='left')

In [227]:
merge

,CBSA Name,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,pop_pct_change
0,"Atlanta-Sandy Springs-Roswell, GA",NaN,NaN,71.971945,68.526673,64.358809,61.345567,61.938421,62.294681,62.427995,61.672589,60.788780,54.219355,51.015677,55.026908,52.448513,48.743033,45.828205,48.163173,44.887319,44.904901,43.214218,41.567224,44.170674,41.661393,44.387061,41.616496,47.210780,40.707072,0.132333
1,"Baltimore-Columbia-Towson, MD",NaN,NaN,62.824925,61.402066,60.354261,59.129313,57.382264,58.145234,59.499710,55.584224,56.180278,54.016698,48.428399,47.844782,47.295553,46.067550,43.458322,43.787059,44.306648,40.857023,38.760179,37.504124,39.591275,33.790063,39.098485,34.339441,44.005513,34.086339,0.031239
2,"Boston-Cambridge-Newton, MA-NH",NaN,NaN,53.015121,51.274769,53.423984,49.144801,48.301866,49.376003,48.274410,42.652092,45.103263,45.955534,41.835347,39.752198,40.036540,40.101608,36.835646,31.199469,32.055512,30.612476,29.394419,28.135560,26.741901,35.515335,40.599395,31.603171,37.192751,31.168128,0.057362
3,"Charlotte-Concord-Gastonia, NC-SC",NaN,NaN,61.263745,62.805688,58.738356,58.356246,57.665661,58.858567,59.905740,58.503773,56.745160,54.760923,48.452519,51.406007,48.371246,45.277453,43.778014,44.218848,41.784050,43.760548,42.299931,39.987182,42.442514,39.366375,42.891730,41.174138,45.967057,36.855556,0.180043
4,"Chicago-Naperville-Elgin, IL-IN-WI",57.121951,64.817948,61.906111,61.029117,61.541239,59.300711,58.109288,55.064670,60.733486,54.565680,57.362744,50.786457,49.275134,51.518536,50.429847,48.988311,48.564876,47.810368,46.145483,42.426197,41.608099,45.248039,43.272777,43.787079,45.135499,44.089014,47.185000,38.336416,NaN
5,"Cincinnati, OH-KY-IN",NaN,NaN,66.045610,66.429202,62.431134,62.300452,61.640908,59.329370,65.330448,57.522166,60.286881,56.333505,54.601768,56.227249,52.621895,51.371128,50.187294,50.463269,47.397648,45.948778,43.543902,44.754969,45.461036,43.027051,45.052552,42.153787,46.260528,41.889259,0.057916
6,"Columbus, OH",NaN,NaN,65.973679,65.645011,64.536280,62.513925,61.620498,58.492328,61.464032,54.985002,57.889854,53.072319,50.437011,53.681544,50.854804,49.302735,47.399805,46.859915,46.816192,42.088701,41.472587,43.032253,43.655614,41.975704,44.300506,40.263206,44.808330,38.244466,0.104538
7,"Dallas-Fort Worth-Arlington, TX",NaN,NaN,55.182665,55.069324,54.474683,53.819476,54.755092,53.056432,55.054705,50.612061,52.077191,49.689446,46.353624,47.832944,49.860525,48.958440,46.389586,47.371336,45.401910,41.800846,43.916453,43.237846,41.089705,42.275868,43.942400,43.240376,44.152778,43.941176,0.164782
8,"Detroit-Warren-Dearborn, MI",NaN,NaN,59.202340,60.974083,61.262894,60.058202,60.204629,58.324330,60.539365,53.755833,54.485865,50.023950,46.036424,43.947819,44.440858,46.000165,43.162480,45.802065,45.004383,41.982959,40.880553,42.244864,40.573002,37.569095,42.449735,39.207912,44.791150,38.160211,0.017465
9,"Fresno, CA",NaN,NaN,76.200502,71.539332,70.661060,72.401381,69.144136,65.473344,64.623546,66.296420,66.026657,63.500509,56.554523,55.415311,58.957581,70.434040,61.414957,55.028686,55.228127,51.851587,56.136841,60.806685,47.905269,65.485126,62.922078,54.940000,49.528455,42.590361,0.234072
10,"Grand Rapids-Wyoming, MI",NaN,NaN,54.310767,54.461693,56.273138,54.852248,54.199199,49.167356,55.227965,51.796298,51.654794,47.892309,45.244669,43.207971,43.167753,43.695348,40.988218,45.033416,44.334227,41.028604,41.854304,40.226608,38.564555,37.553842,38.305263,35.684211,41.365385,29.826087,NaN
11,"Hartford-West Hartford-East Hartford, CT",NaN,NaN,47.772321,47.238255,51.399381,50.013559,50.573964,48.032738,49.487179,46.089231,44.478754,46.870080,40.864988,38.408042,42.847394,38.868874,38.522847,38.185724,40.932065,35.535394,33.816686,33.891371,29.815055,32.719298,35.180328,31.631579,36.700000,28.193548,-0.058550
12,"Jacksonville, FL",NaN,NaN,53.388784,53.326779,50.479710,45.976707,46.619451,49.433205,47.685469,46.955565,46.512835,43.974133,40.558651,43.180302,NaN,38.210476,34.959461,38.840961,37.636329,38.544950,37.992520,37.381577,35.848995,35.511111,34.764286,38.019868,NaN,NaN,0.191682
13,"Kansas City, MO-KS",NaN,NaN,54.360971,53.025627,53.839762,53.733197,53.135034,51.615406,53.670732,50.087858,50.855896,49.053256,46.371710,47.857122,46.853209,44.371389,42.750521,44.918913,42.507790,39.971202,45.829713,45.216750,42.323743,39.052937,45.691273,43.955002,47.914721,40.101124,0.078955
14,"Los Angeles-Long Beach-Anaheim, CA",NaN,NaN,72.399439,68.359661,69.317498,69.013847,65.299108,62.783797,60.427711,56.959251,57.974208,55.071509,53.689529,48.538945,49.902546,48.388306,50.611558,54.210913,48.063064,48.146789,50.333665,50.932957,45.918922,53.079805,51.674487,49.678424,47.737663,44.718164,-0.003680
15,"Louisville/Jefferson County, KY-IN",NaN,NaN,62.229327,64.179449,64.263861,62.076460,61.151728,57.788092,64.356408,58.462646,60.938260,56.023097,53.083512,56.841523,52.069857,49.434306,48.828518,50.162578,45.696597,42.517389,41.433509,43.727356,42.497176,41.436097,43.967947,41.795408,45.173554,39.852778,0.086605
16,"Memphis, TN-MS-AR",NaN,NaN,61.513343,58.817803,54.658592,54.053019,54.205813,52.998757,56.762728,54.849495,54.293949,52.534662,47.421383,50.831780,49.987681,47.622951,45.399114,44.202786,42.414804,40.490986,41.747774,42.163459,41.587417,39.047051,40.546573,41.336095,44.609903,41.997235,0.003435
17,"Miami-Fort Lauderdale-West Palm Beach, FL",NaN,NaN,46.092052,46.638670,39.636587,40.332215,40.143955,42.233755,42.127480,40.157515,38.186711,36.094528,33.736769,36.243615,NaN,36.425673,32.995323,33.028562,31.694569,35.388122,37.485163,35.598526,33.769057,34.840954,36.790880,34.493470,37.815368,39.899058,0.062971
18,"Minneapolis-St. Paul-Bloomington, MN-WI",NaN,NaN,46.187987,50.160010,47.870981,46.669032,45.342047,40.761473,45.293105,43.648130,44.612075,45.463257,42.966361,42.828372,41.475320,43.002274,42.366958,41.438823,36.333521,33.050869,34.399530,38.805773,36.289994,37.808005,41.172283,34.660547,43.331048,31.473695,0.078418
19,"Nashville-Davidson--Murfreesboro--Franklin, TN",NaN,NaN,64.787314,62.105622,57.143387,54.774269,57.878345,54.746164,58.529527,56.888914,55.538045,NaN,NaN,NaN,NaN,NaN,44.588217,46.195829,42.567112,41.015912,40.221338,41.411011,40.250174,43.647268,41.563307,40.636475,45.655524,37.122679,0.180985
20,"New York-Newark-Jersey City, NY-NJ-PA",NaN,NaN,57.063061,57.740361,56.302782,55.604058,55.357104,53.322619,57.106314,50.871693,53.594410,51.796663,44.927129,43.533207,46.032854,44.664274,42.372420,43.150256,42.682005,39.181181,38.691812,38.899645,37.448864,37.652707,38.965385,36.004929,41.138967,32.578617,NaN
21,"Oklahoma City, OK",NaN,NaN,45.696609,47.889185,46.411991,44.826033,47.096464,44.833847,47.678719,43.460973,50.745984,48.987706,44.711389,44.877828,46.806510,46.458141,43.891956,43.153623,40.401052,38.536694,38.541400,42.713102,36.789323,36.445709,42.975743,38.656206,41.265044,38.982163,0.113347
22,"Orlando-Kissimmee-Sanford, FL",NaN,NaN,50.541390,51.948454,48.727205,45.199060,45.395543,48.017096,46.500218,45.188591,43.633136,39.444137,37.714006,39.963019,NaN,36.402783,32.533588,34.183935,31.989924,34.541523,34.166667,33.888889,30.900000,31.032258,31.730769,36.500000,38.607143,36.466667,0.221923
23,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NaN,NaN,56.266134,59.108705,59.042865,57.525469,57.064044,54.791619,57.277661,53.200035,54.868873,53.759419,47.964220,45.748218,46.598614,45.415311,44.767048,45.039646,43.674674,40.490269,39.413405,37.624584,37.475346,37.118793,39.829445,35.627998,41.822321,34.208422,0.037661
24,"Pittsburgh, PA",NaN,NaN,62.613115,60.804772,62.694098,59.649530,59.477979,59.694072,62.271141,57.155039,59.585515,55.715228,52.135186,53.408779,50.090263,48.569181,46.596011,46.955749,46.280768,44.855678,46.723997,44.329551,43.118617,39.453172,44.183065,40.386488,44.100491,36.342984,0.036090
25,"Portland-Vancouver-Hillsboro, OR-WA",NaN,NaN,41.090617,42.211747,39.349114,39.093654,38.043604,40.385790,43.450596,45.839286,36.892684,39.574001,38.922110,31.615244,37.325161,35.251928,42.893114,33.158333,36.750597,30.927178,36.842140,36.203977,34.309197,37.403968,32.677297,36.587015,30.756885,23.263158,0.096878
26,"Providence-Warwick, RI-MA",NaN,NaN,45.407378,45.948907,48.840815,45.416636,48.004742,47.654191,47.557702,43.055480,44.110866,44.091661,39.341667,38.075224,40.893115,38.907300,37.089001,33.052526,33.931611,31.190670,29.676134,29.190393,29.317614,39.938636,44.742932,32.713690,37.072787,28.126572,0.043314
27,"Raleigh, NC",NaN,NaN,61.634069,62.326733,58.394299,57.104369,57.175309,55.784062,55.655405,56.510965,55.622449,50.564548,44.174510,47.679166,45.243272,41.815134,40.462318,42.750650,38.527836,40.100102,39.989481,38.893443,40.537037,31.292683,40.280702,36.950000,42.743119,36.711864,NaN
28,"Richmond, VA",NaN,NaN,58.096372,59.391293,56.316706,56.169980,55.260047,54.485760,56.459481,53.946197,53.192821,49.199304,44.242063,46.399684,44.159186,42.589408,40.526094,41.625130,39.954883,38.549921,38.514686,36.420298,36.921052,32.053438,37.899686,33.299929,39.994643,34.617449,0.075574
29,"Riverside-San Bernardino-Ontario, CA",NaN,NaN,72.111018,67.188652,69.870665,68.919113,64.263961,60.974617,58.059435,58.845037,59.009586,52.756329,51.177454,46.188259,46.114775,46.725260,46.878672,47.971898,47.796375,44.988688,44.375066,46.887728,41.752087,45.396913,45.605328,42.868364,42.563151,42.404521,0.067251
30,"Rochester, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.729167,51.281818,42.966387,43.361345,42.547826,38.085470,39.324324,42.021978,42.504854,36.170940,37.016667,38.873639,32.853258,34.727959,35.834030,33.671665,30.760940,35.087002,30.893964,38.236017,29.625000,-0.021895
31,"Salt Lake City, UT",NaN,NaN,44.391320,46.344841,47.380415,51.330618,43.181813,55.058707,46.657580,43.594702,47.647688,43.541771,42.116757,37.933094,34.919962,36.439303,43.327250,32.177345,38.580560,37.630675,37.594217,39.953970,32.717803,37.085921,41.140407,36.992201,33.759915,31.845290,NaN
32,"San Antonio-New Braunfels, TX",NaN,NaN,57.042857,47.311932,42.816224,44.294639,43.427294,NaN,NaN,NaN,NaN,43.183111,44.840414,43.667832,44.770569,42.666667,39.510558,43.166667,41.492589,40.204070,42.331393,39.546164,41.774194,41.903226,39.633333,42.193548,38.444444,53.444444,0.166835
33,"San Jose-Sunnyvale-Santa Clara, CA",NaN,NaN,70.095029,60.921498,55.874278,58.161128,52.137928,53.460625,52.559583,48.733452,40.143707,43.193802,38.649917,44.155340,47.716102,43.531073,46.824000,44.563025,48.102564,41.178947,45.837838,48.592000,38.774194,48.235772,41.655738,44.641667,38.162393,NaN,0.037344
34,"Seattle-Tacoma-Bellevue, WA",NaN,NaN,46.162445,49.313357,46.221545,43.382621,42.102766,40.341717,44.470690,41.777240,39.342152,39.400304,40.460030,32.567133,33.715500,35.738265,33.348455,31.628111,33.336066,31.786821,33.581325,34.327455,35.805186,34.413949,33.155237,32.750379,29.126954,29.004396,0.130567
35,"St. Louis, MO-IL",NaN,NaN,63.363965,63.162146,60.783063,61.278575,58.883231,56.307124,62.496751,56.485199,58.452735,54.099829,51.365480,55.159257,53.191957,48.584951,50.063260,50.637724,47.554339,44.471235,44.331312,47.608503,46.296570,45.976563,45.861047,45.320369,46.761845,40.939175,0.004174
36,"Tampa-St. Petersburg-Clearwater, FL",NaN,NaN,54.404464,54.488795,51.583593,49.908265,47.451932,50.129347,49.252028,46.966062,46.519886,42.309202,39.980627,43.303575,NaN,36.841426,34.171064,35.069116,36.560979,37.232415,39.821838,37.038542,36.248677,39.659091,38.821429,38.789116,40.861314,40.114754,0.136514
37,"Tucson, AZ",NaN,NaN,44.144951,38.717317,39.121875,34.183206,34.848685,31.092004,33.499627,31.693203,30.929293,30.173875,29.358919,27.885150,30.302089,30.929752,27.858861,32.787178,28.187500,33.161811,35.062031,32.233333,27.578431,32.801653,33.137931,32.663866,28.641026,29.988235,0.057195
38,"Tulsa, OK",NaN,NaN,51.600791,50.089431,48.638270,45.207262,47.299745,48.475885,52.647230,49.479429,53.558404,51.972191,49.363749,50.815812,50.376404,46.698068,44.461353,43.622951,41.110482,39.575581,39.096591,40.729885,36.441341,35.211111,38.878788,39.000000,42.587209,39.815217,0.075629
39,"Urban Honolulu, HI",NaN,NaN,24.142399,22.755795,24.207283,23.000198,24.238941,21.292307,23.191221,21.807081,21.912940,26.357724,26.744444,19.740741,18.721739,20.754386,19.921739,NaN,NaN,NaN,NaN,24.009524,19.943925,19.818116,17.208333,21.404520,19.264921,19.491071,0.028673
40,"Washington-Arlington-Alexandria, DC-VA-MD-WV",NaN,NaN,57.976664,59.689804,58.838144,58.183780,55.326038,55.298357,57.750099,53.381486,54.735026,51.910036,46.188450,47.594307,45.646976,44.316919,42.204747,42.768215,42.901663,38.775045,38.139825,37.972033,37.056526,31.953383,40.043225,35.515838,38.285050,32.813553,0.068249

In [228]:
# Manually fill in missing pop_pct_change values
merge.loc[merge['CBSA Name'] == 'Chicago-Naperville-Elgin, IL-IN-WI', 'pop_pct_change'] = -0.016487
merge.loc[merge['CBSA Name'] == 'Grand Rapids-Wyoming, MI', 'pop_pct_change'] = 0.145922
merge.loc[merge['CBSA Name'] == 'New York-Newark-Jersey City, NY-NJ-PA', 'pop_pct_change'] = -0.005453
merge.loc[merge['CBSA Name'] == 'Raleigh, NC', 'pop_pct_change'] = 0.218577
merge.loc[merge['CBSA Name'] == 'Salt Lake City, UT', 'pop_pct_change'] = 0.122542

In [229]:
merge

,CBSA Name,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,pop_pct_change
0,"Atlanta-Sandy Springs-Roswell, GA",NaN,NaN,71.971945,68.526673,64.358809,61.345567,61.938421,62.294681,62.427995,61.672589,60.788780,54.219355,51.015677,55.026908,52.448513,48.743033,45.828205,48.163173,44.887319,44.904901,43.214218,41.567224,44.170674,41.661393,44.387061,41.616496,47.210780,40.707072,0.132333
1,"Baltimore-Columbia-Towson, MD",NaN,NaN,62.824925,61.402066,60.354261,59.129313,57.382264,58.145234,59.499710,55.584224,56.180278,54.016698,48.428399,47.844782,47.295553,46.067550,43.458322,43.787059,44.306648,40.857023,38.760179,37.504124,39.591275,33.790063,39.098485,34.339441,44.005513,34.086339,0.031239
2,"Boston-Cambridge-Newton, MA-NH",NaN,NaN,53.015121,51.274769,53.423984,49.144801,48.301866,49.376003,48.274410,42.652092,45.103263,45.955534,41.835347,39.752198,40.036540,40.101608,36.835646,31.199469,32.055512,30.612476,29.394419,28.135560,26.741901,35.515335,40.599395,31.603171,37.192751,31.168128,0.057362
3,"Charlotte-Concord-Gastonia, NC-SC",NaN,NaN,61.263745,62.805688,58.738356,58.356246,57.665661,58.858567,59.905740,58.503773,56.745160,54.760923,48.452519,51.406007,48.371246,45.277453,43.778014,44.218848,41.784050,43.760548,42.299931,39.987182,42.442514,39.366375,42.891730,41.174138,45.967057,36.855556,0.180043
4,"Chicago-Naperville-Elgin, IL-IN-WI",57.121951,64.817948,61.906111,61.029117,61.541239,59.300711,58.109288,55.064670,60.733486,54.565680,57.362744,50.786457,49.275134,51.518536,50.429847,48.988311,48.564876,47.810368,46.145483,42.426197,41.608099,45.248039,43.272777,43.787079,45.135499,44.089014,47.185000,38.336416,-0.016487
5,"Cincinnati, OH-KY-IN",NaN,NaN,66.045610,66.429202,62.431134,62.300452,61.640908,59.329370,65.330448,57.522166,60.286881,56.333505,54.601768,56.227249,52.621895,51.371128,50.187294,50.463269,47.397648,45.948778,43.543902,44.754969,45.461036,43.027051,45.052552,42.153787,46.260528,41.889259,0.057916
6,"Columbus, OH",NaN,NaN,65.973679,65.645011,64.536280,62.513925,61.620498,58.492328,61.464032,54.985002,57.889854,53.072319,50.437011,53.681544,50.854804,49.302735,47.399805,46.859915,46.816192,42.088701,41.472587,43.032253,43.655614,41.975704,44.300506,40.263206,44.808330,38.244466,0.104538
7,"Dallas-Fort Worth-Arlington, TX",NaN,NaN,55.182665,55.069324,54.474683,53.819476,54.755092,53.056432,55.054705,50.612061,52.077191,49.689446,46.353624,47.832944,49.860525,48.958440,46.389586,47.371336,45.401910,41.800846,43.916453,43.237846,41.089705,42.275868,43.942400,43.240376,44.152778,43.941176,0.164782
8,"Detroit-Warren-Dearborn, MI",NaN,NaN,59.202340,60.974083,61.262894,60.058202,60.204629,58.324330,60.539365,53.755833,54.485865,50.023950,46.036424,43.947819,44.440858,46.000165,43.162480,45.802065,45.004383,41.982959,40.880553,42.244864,40.573002,37.569095,42.449735,39.207912,44.791150,38.160211,0.017465
9,"Fresno, CA",NaN,NaN,76.200502,71.539332,70.661060,72.401381,69.144136,65.473344,64.623546,66.296420,66.026657,63.500509,56.554523,55.415311,58.957581,70.434040,61.414957,55.028686,55.228127,51.851587,56.136841,60.806685,47.905269,65.485126,62.922078,54.940000,49.528455,42.590361,0.234072
10,"Grand Rapids-Wyoming, MI",NaN,NaN,54.310767,54.461693,56.273138,54.852248,54.199199,49.167356,55.227965,51.796298,51.654794,47.892309,45.244669,43.207971,43.167753,43.695348,40.988218,45.033416,44.334227,41.028604,41.854304,40.226608,38.564555,37.553842,38.305263,35.684211,41.365385,29.826087,0.145922
11,"Hartford-West Hartford-East Hartford, CT",NaN,NaN,47.772321,47.238255,51.399381,50.013559,50.573964,48.032738,49.487179,46.089231,44.478754,46.870080,40.864988,38.408042,42.847394,38.868874,38.522847,38.185724,40.932065,35.535394,33.816686,33.891371,29.815055,32.719298,35.180328,31.631579,36.700000,28.193548,-0.058550
12,"Jacksonville, FL",NaN,NaN,53.388784,53.326779,50.479710,45.976707,46.619451,49.433205,47.685469,46.955565,46.512835,43.974133,40.558651,43.180302,NaN,38.210476,34.959461,38.840961,37.636329,38.544950,37.992520,37.381577,35.848995,35.511111,34.764286,38.019868,NaN,NaN,0.191682
13,"Kansas City, MO-KS",NaN,NaN,54.360971,53.025627,53.839762,53.733197,53.135034,51.615406,53.670732,50.087858,50.855896,49.053256,46.371710,47.857122,46.853209,44.371389,42.750521,44.918913,42.507790,39.971202,45.829713,45.216750,42.323743,39.052937,45.691273,43.955002,47.914721,40.101124,0.078955
14,"Los Angeles-Long Beach-Anaheim, CA",NaN,NaN,72.399439,68.359661,69.317498,69.013847,65.299108,62.783797,60.427711,56.959251,57.974208,55.071509,53.689529,48.538945,49.902546,48.388306,50.611558,54.210913,48.063064,48.146789,50.333665,50.932957,45.918922,53.079805,51.674487,49.678424,47.737663,44.718164,-0.003680
15,"Louisville/Jefferson County, KY-IN",NaN,NaN,62.229327,64.179449,64.263861,62.076460,61.151728,57.788092,64.356408,58.462646,60.938260,56.023097,53.083512,56.841523,52.069857,49.434306,48.828518,50.162578,45.696597,42.517389,41.433509,43.727356,42.497176,41.436097,43.967947,41.795408,45.173554,39.852778,0.086605
16,"Memphis, TN-MS-AR",NaN,NaN,61.513343,58.817803,54.658592,54.053019,54.205813,52.998757,56.762728,54.849495,54.293949,52.534662,47.421383,50.831780,49.987681,47.622951,45.399114,44.202786,42.414804,40.490986,41.747774,42.163459,41.587417,39.047051,40.546573,41.336095,44.609903,41.997235,0.003435
17,"Miami-Fort Lauderdale-West Palm Beach, FL",NaN,NaN,46.092052,46.638670,39.636587,40.332215,40.143955,42.233755,42.127480,40.157515,38.186711,36.094528,33.736769,36.243615,NaN,36.425673,32.995323,33.028562,31.694569,35.388122,37.485163,35.598526,33.769057,34.840954,36.790880,34.493470,37.815368,39.899058,0.062971
18,"Minneapolis-St. Paul-Bloomington, MN-WI",NaN,NaN,46.187987,50.160010,47.870981,46.669032,45.342047,40.761473,45.293105,43.648130,44.612075,45.463257,42.966361,42.828372,41.475320,43.002274,42.366958,41.438823,36.333521,33.050869,34.399530,38.805773,36.289994,37.808005,41.172283,34.660547,43.331048,31.473695,0.078418
19,"Nashville-Davidson--Murfreesboro--Franklin, TN",NaN,NaN,64.787314,62.105622,57.143387,54.774269,57.878345,54.746164,58.529527,56.888914,55.538045,NaN,NaN,NaN,NaN,NaN,44.588217,46.195829,42.567112,41.015912,40.221338,41.411011,40.250174,43.647268,41.563307,40.636475,45.655524,37.122679,0.180985
20,"New York-Newark-Jersey City, NY-NJ-PA",NaN,NaN,57.063061,57.740361,56.302782,55.604058,55.357104,53.322619,57.106314,50.871693,53.594410,51.796663,44.927129,43.533207,46.032854,44.664274,42.372420,43.150256,42.682005,39.181181,38.691812,38.899645,37.448864,37.652707,38.965385,36.004929,41.138967,32.578617,-0.005453
21,"Oklahoma City, OK",NaN,NaN,45.696609,47.889185,46.411991,44.826033,47.096464,44.833847,47.678719,43.460973,50.745984,48.987706,44.711389,44.877828,46.806510,46.458141,43.891956,43.153623,40.401052,38.536694,38.541400,42.713102,36.789323,36.445709,42.975743,38.656206,41.265044,38.982163,0.113347
22,"Orlando-Kissimmee-Sanford, FL",NaN,NaN,50.541390,51.948454,48.727205,45.199060,45.395543,48.017096,46.500218,45.188591,43.633136,39.444137,37.714006,39.963019,NaN,36.402783,32.533588,34.183935,31.989924,34.541523,34.166667,33.888889,30.900000,31.032258,31.730769,36.500000,38.607143,36.466667,0.221923
23,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NaN,NaN,56.266134,59.108705,59.042865,57.525469,57.064044,54.791619,57.277661,53.200035,54.868873,53.759419,47.964220,45.748218,46.598614,45.415311,44.767048,45.039646,43.674674,40.490269,39.413405,37.624584,37.475346,37.118793,39.829445,35.627998,41.822321,34.208422,0.037661
24,"Pittsburgh, PA",NaN,NaN,62.613115,60.804772,62.694098,59.649530,59.477979,59.694072,62.271141,57.155039,59.585515,55.715228,52.135186,53.408779,50.090263,48.569181,46.596011,46.955749,46.280768,44.855678,46.723997,44.329551,43.118617,39.453172,44.183065,40.386488,44.100491,36.342984,0.036090
25,"Portland-Vancouver-Hillsboro, OR-WA",NaN,NaN,41.090617,42.211747,39.349114,39.093654,38.043604,40.385790,43.450596,45.839286,36.892684,39.574001,38.922110,31.615244,37.325161,35.251928,42.893114,33.158333,36.750597,30.927178,36.842140,36.203977,34.309197,37.403968,32.677297,36.587015,30.756885,23.263158,0.096878
26,"Providence-Warwick, RI-MA",NaN,NaN,45.407378,45.948907,48.840815,45.416636,48.004742,47.654191,47.557702,43.055480,44.110866,44.091661,39.341667,38.075224,40.893115,38.907300,37.089001,33.052526,33.931611,31.190670,29.676134,29.190393,29.317614,39.938636,44.742932,32.713690,37.072787,28.126572,0.043314
27,"Raleigh, NC",NaN,NaN,61.634069,62.326733,58.394299,57.104369,57.175309,55.784062,55.655405,56.510965,55.622449,50.564548,44.174510,47.679166,45.243272,41.815134,40.462318,42.750650,38.527836,40.100102,39.989481,38.893443,40.537037,31.292683,40.280702,36.950000,42.743119,36.711864,0.218577
28,"Richmond, VA",NaN,NaN,58.096372,59.391293,56.316706,56.169980,55.260047,54.485760,56.459481,53.946197,53.192821,49.199304,44.242063,46.399684,44.159186,42.589408,40.526094,41.625130,39.954883,38.549921,38.514686,36.420298,36.921052,32.053438,37.899686,33.299929,39.994643,34.617449,0.075574
29,"Riverside-San Bernardino-Ontario, CA",NaN,NaN,72.111018,67.188652,69.870665,68.919113,64.263961,60.974617,58.059435,58.845037,59.009586,52.756329,51.177454,46.188259,46.114775,46.725260,46.878672,47.971898,47.796375,44.988688,44.375066,46.887728,41.752087,45.396913,45.605328,42.868364,42.563151,42.404521,0.067251
30,"Rochester, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.729167,51.281818,42.966387,43.361345,42.547826,38.085470,39.324324,42.021978,42.504854,36.170940,37.016667,38.873639,32.853258,34.727959,35.834030,33.671665,30.760940,35.087002,30.893964,38.236017,29.625000,-0.021895
31,"Salt Lake City, UT",NaN,NaN,44.391320,46.344841,47.380415,51.330618,43.181813,55.058707,46.657580,43.594702,47.647688,43.541771,42.116757,37.933094,34.919962,36.439303,43.327250,32.177345,38.580560,37.630675,37.594217,39.953970,32.717803,37.085921,41.140407,36.992201,33.759915,31.845290,0.122542
32,"San Antonio-New Braunfels, TX",NaN,NaN,57.042857,47.311932,42.816224,44.294639,43.427294,NaN,NaN,NaN,NaN,43.183111,44.840414,43.667832,44.770569,42.666667,39.510558,43.166667,41.492589,40.204070,42.331393,39.546164,41.774194,41.903226,39.633333,42.193548,38.444444,53.444444,0.166835
33,"San Jose-Sunnyvale-Santa Clara, CA",NaN,NaN,70.095029,60.921498,55.874278,58.161128,52.137928,53.460625,52.559583,48.733452,40.143707,43.193802,38.649917,44.155340,47.716102,43.531073,46.824000,44.563025,48.102564,41.178947,45.837838,48.592000,38.774194,48.235772,41.655738,44.641667,38.162393,NaN,0.037344
34,"Seattle-Tacoma-Bellevue, WA",NaN,NaN,46.162445,49.313357,46.221545,43.382621,42.102766,40.341717,44.470690,41.777240,39.342152,39.400304,40.460030,32.567133,33.715500,35.738265,33.348455,31.628111,33.336066,31.786821,33.581325,34.327455,35.805186,34.413949,33.155237,32.750379,29.126954,29.004396,0.130567
35,"St. Louis, MO-IL",NaN,NaN,63.363965,63.162146,60.783063,61.278575,58.883231,56.307124,62.496751,56.485199,58.452735,54.099829,51.365480,55.159257,53.191957,48.584951,50.063260,50.637724,47.554339,44.471235,44.331312,47.608503,46.296570,45.976563,45.861047,45.320369,46.761845,40.939175,0.004174
36,"Tampa-St. Petersburg-Clearwater, FL",NaN,NaN,54.404464,54.488795,51.583593,49.908265,47.451932,50.129347,49.252028,46.966062,46.519886,42.309202,39.980627,43.303575,NaN,36.841426,34.171064,35.069116,36.560979,37.232415,39.821838,37.038542,36.248677,39.659091,38.821429,38.789116,40.861314,40.114754,0.136514
37,"Tucson, AZ",NaN,NaN,44.144951,38.717317,39.121875,34.183206,34.848685,31.092004,33.499627,31.693203,30.929293,30.173875,29.358919,27.885150,30.302089,30.929752,27.858861,32.787178,28.187500,33.161811,35.062031,32.233333,27.578431,32.801653,33.137931,32.663866,28.641026,29.988235,0.057195
38,"Tulsa, OK",NaN,NaN,51.600791,50.089431,48.638270,45.207262,47.299745,48.475885,52.647230,49.479429,53.558404,51.972191,49.363749,50.815812,50.376404,46.698068,44.461353,43.622951,41.110482,39.575581,39.096591,40.729885,36.441341,35.211111,38.878788,39.000000,42.587209,39.815217,0.075629
39,"Urban Honolulu, HI",NaN,NaN,24.142399,22.755795,24.207283,23.000198,24.238941,21.292307,23.191221,21.807081,21.912940,26.357724,26.744444,19.740741,18.721739,20.754386,19.921739,NaN,NaN,NaN,NaN,24.009524,19.943925,19.818116,17.208333,21.404520,19.264921,19.491071,0.028673
40,"Washington-Arlington-Alexandria, DC-VA-MD-WV",NaN,NaN,57.976664,59.689804,58.838144,58.183780,55.326038,55.298357,57.750099,53.381486,54.735026,51.910036,46.188450,47.594307,45.646976,44.316919,42.204747,42.768215,42.901663,38.775045,38.139825,37.972033,37.056526,31.953383,40.043225,35.515838,38.285050,32.813553,0.068249

In [230]:
merge = merge.sort_values(by='pop_pct_change',ascending=False)

In [231]:
merge

,CBSA Name,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,pop_pct_change
9,"Fresno, CA",NaN,NaN,76.200502,71.539332,70.661060,72.401381,69.144136,65.473344,64.623546,66.296420,66.026657,63.500509,56.554523,55.415311,58.957581,70.434040,61.414957,55.028686,55.228127,51.851587,56.136841,60.806685,47.905269,65.485126,62.922078,54.940000,49.528455,42.590361,0.234072
22,"Orlando-Kissimmee-Sanford, FL",NaN,NaN,50.541390,51.948454,48.727205,45.199060,45.395543,48.017096,46.500218,45.188591,43.633136,39.444137,37.714006,39.963019,NaN,36.402783,32.533588,34.183935,31.989924,34.541523,34.166667,33.888889,30.900000,31.032258,31.730769,36.500000,38.607143,36.466667,0.221923
27,"Raleigh, NC",NaN,NaN,61.634069,62.326733,58.394299,57.104369,57.175309,55.784062,55.655405,56.510965,55.622449,50.564548,44.174510,47.679166,45.243272,41.815134,40.462318,42.750650,38.527836,40.100102,39.989481,38.893443,40.537037,31.292683,40.280702,36.950000,42.743119,36.711864,0.218577
12,"Jacksonville, FL",NaN,NaN,53.388784,53.326779,50.479710,45.976707,46.619451,49.433205,47.685469,46.955565,46.512835,43.974133,40.558651,43.180302,NaN,38.210476,34.959461,38.840961,37.636329,38.544950,37.992520,37.381577,35.848995,35.511111,34.764286,38.019868,NaN,NaN,0.191682
19,"Nashville-Davidson--Murfreesboro--Franklin, TN",NaN,NaN,64.787314,62.105622,57.143387,54.774269,57.878345,54.746164,58.529527,56.888914,55.538045,NaN,NaN,NaN,NaN,NaN,44.588217,46.195829,42.567112,41.015912,40.221338,41.411011,40.250174,43.647268,41.563307,40.636475,45.655524,37.122679,0.180985
3,"Charlotte-Concord-Gastonia, NC-SC",NaN,NaN,61.263745,62.805688,58.738356,58.356246,57.665661,58.858567,59.905740,58.503773,56.745160,54.760923,48.452519,51.406007,48.371246,45.277453,43.778014,44.218848,41.784050,43.760548,42.299931,39.987182,42.442514,39.366375,42.891730,41.174138,45.967057,36.855556,0.180043
32,"San Antonio-New Braunfels, TX",NaN,NaN,57.042857,47.311932,42.816224,44.294639,43.427294,NaN,NaN,NaN,NaN,43.183111,44.840414,43.667832,44.770569,42.666667,39.510558,43.166667,41.492589,40.204070,42.331393,39.546164,41.774194,41.903226,39.633333,42.193548,38.444444,53.444444,0.166835
7,"Dallas-Fort Worth-Arlington, TX",NaN,NaN,55.182665,55.069324,54.474683,53.819476,54.755092,53.056432,55.054705,50.612061,52.077191,49.689446,46.353624,47.832944,49.860525,48.958440,46.389586,47.371336,45.401910,41.800846,43.916453,43.237846,41.089705,42.275868,43.942400,43.240376,44.152778,43.941176,0.164782
10,"Grand Rapids-Wyoming, MI",NaN,NaN,54.310767,54.461693,56.273138,54.852248,54.199199,49.167356,55.227965,51.796298,51.654794,47.892309,45.244669,43.207971,43.167753,43.695348,40.988218,45.033416,44.334227,41.028604,41.854304,40.226608,38.564555,37.553842,38.305263,35.684211,41.365385,29.826087,0.145922
36,"Tampa-St. Petersburg-Clearwater, FL",NaN,NaN,54.404464,54.488795,51.583593,49.908265,47.451932,50.129347,49.252028,46.966062,46.519886,42.309202,39.980627,43.303575,NaN,36.841426,34.171064,35.069116,36.560979,37.232415,39.821838,37.038542,36.248677,39.659091,38.821429,38.789116,40.861314,40.114754,0.136514
0,"Atlanta-Sandy Springs-Roswell, GA",NaN,NaN,71.971945,68.526673,64.358809,61.345567,61.938421,62.294681,62.427995,61.672589,60.788780,54.219355,51.015677,55.026908,52.448513,48.743033,45.828205,48.163173,44.887319,44.904901,43.214218,41.567224,44.170674,41.661393,44.387061,41.616496,47.210780,40.707072,0.132333
34,"Seattle-Tacoma-Bellevue, WA",NaN,NaN,46.162445,49.313357,46.221545,43.382621,42.102766,40.341717,44.470690,41.777240,39.342152,39.400304,40.460030,32.567133,33.715500,35.738265,33.348455,31.628111,33.336066,31.786821,33.581325,34.327455,35.805186,34.413949,33.155237,32.750379,29.126954,29.004396,0.130567
31,"Salt Lake City, UT",NaN,NaN,44.391320,46.344841,47.380415,51.330618,43.181813,55.058707,46.657580,43.594702,47.647688,43.541771,42.116757,37.933094,34.919962,36.439303,43.327250,32.177345,38.580560,37.630675,37.594217,39.953970,32.717803,37.085921,41.140407,36.992201,33.759915,31.845290,0.122542
21,"Oklahoma City, OK",NaN,NaN,45.696609,47.889185,46.411991,44.826033,47.096464,44.833847,47.678719,43.460973,50.745984,48.987706,44.711389,44.877828,46.806510,46.458141,43.891956,43.153623,40.401052,38.536694,38.541400,42.713102,36.789323,36.445709,42.975743,38.656206,41.265044,38.982163,0.113347
6,"Columbus, OH",NaN,NaN,65.973679,65.645011,64.536280,62.513925,61.620498,58.492328,61.464032,54.985002,57.889854,53.072319,50.437011,53.681544,50.854804,49.302735,47.399805,46.859915,46.816192,42.088701,41.472587,43.032253,43.655614,41.975704,44.300506,40.263206,44.808330,38.244466,0.104538
25,"Portland-Vancouver-Hillsboro, OR-WA",NaN,NaN,41.090617,42.211747,39.349114,39.093654,38.043604,40.385790,43.450596,45.839286,36.892684,39.574001,38.922110,31.615244,37.325161,35.251928,42.893114,33.158333,36.750597,30.927178,36.842140,36.203977,34.309197,37.403968,32.677297,36.587015,30.756885,23.263158,0.096878
15,"Louisville/Jefferson County, KY-IN",NaN,NaN,62.229327,64.179449,64.263861,62.076460,61.151728,57.788092,64.356408,58.462646,60.938260,56.023097,53.083512,56.841523,52.069857,49.434306,48.828518,50.162578,45.696597,42.517389,41.433509,43.727356,42.497176,41.436097,43.967947,41.795408,45.173554,39.852778,0.086605
13,"Kansas City, MO-KS",NaN,NaN,54.360971,53.025627,53.839762,53.733197,53.135034,51.615406,53.670732,50.087858,50.855896,49.053256,46.371710,47.857122,46.853209,44.371389,42.750521,44.918913,42.507790,39.971202,45.829713,45.216750,42.323743,39.052937,45.691273,43.955002,47.914721,40.101124,0.078955
18,"Minneapolis-St. Paul-Bloomington, MN-WI",NaN,NaN,46.187987,50.160010,47.870981,46.669032,45.342047,40.761473,45.293105,43.648130,44.612075,45.463257,42.966361,42.828372,41.475320,43.002274,42.366958,41.438823,36.333521,33.050869,34.399530,38.805773,36.289994,37.808005,41.172283,34.660547,43.331048,31.473695,0.078418
38,"Tulsa, OK",NaN,NaN,51.600791,50.089431,48.638270,45.207262,47.299745,48.475885,52.647230,49.479429,53.558404,51.972191,49.363749,50.815812,50.376404,46.698068,44.461353,43.622951,41.110482,39.575581,39.096591,40.729885,36.441341,35.211111,38.878788,39.000000,42.587209,39.815217,0.075629
28,"Richmond, VA",NaN,NaN,58.096372,59.391293,56.316706,56.169980,55.260047,54.485760,56.459481,53.946197,53.192821,49.199304,44.242063,46.399684,44.159186,42.589408,40.526094,41.625130,39.954883,38.549921,38.514686,36.420298,36.921052,32.053438,37.899686,33.299929,39.994643,34.617449,0.075574
40,"Washington-Arlington-Alexandria, DC-VA-MD-WV",NaN,NaN,57.976664,59.689804,58.838144,58.183780,55.326038,55.298357,57.750099,53.381486,54.735026,51.910036,46.188450,47.594307,45.646976,44.316919,42.204747,42.768215,42.901663,38.775045,38.139825,37.972033,37.056526,31.953383,40.043225,35.515838,38.285050,32.813553,0.068249
29,"Riverside-San Bernardino-Ontario, CA",NaN,NaN,72.111018,67.188652,69.870665,68.919113,64.263961,60.974617,58.059435,58.845037,59.009586,52.756329,51.177454,46.188259,46.114775,46.725260,46.878672,47.971898,47.796375,44.988688,44.375066,46.887728,41.752087,45.396913,45.605328,42.868364,42.563151,42.404521,0.067251
17,"Miami-Fort Lauderdale-West Palm Beach, FL",NaN,NaN,46.092052,46.638670,39.636587,40.332215,40.143955,42.233755,42.127480,40.157515,38.186711,36.094528,33.736769,36.243615,NaN,36.425673,32.995323,33.028562,31.694569,35.388122,37.485163,35.598526,33.769057,34.840954,36.790880,34.493470,37.815368,39.899058,0.062971
5,"Cincinnati, OH-KY-IN",NaN,NaN,66.045610,66.429202,62.431134,62.300452,61.640908,59.329370,65.330448,57.522166,60.286881,56.333505,54.601768,56.227249,52.621895,51.371128,50.187294,50.463269,47.397648,45.948778,43.543902,44.754969,45.461036,43.027051,45.052552,42.153787,46.260528,41.889259,0.057916
2,"Boston-Cambridge-Newton, MA-NH",NaN,NaN,53.015121,51.274769,53.423984,49.144801,48.301866,49.376003,48.274410,42.652092,45.103263,45.955534,41.835347,39.752198,40.036540,40.101608,36.835646,31.199469,32.055512,30.612476,29.394419,28.135560,26.741901,35.515335,40.599395,31.603171,37.192751,31.168128,0.057362
37,"Tucson, AZ",NaN,NaN,44.144951,38.717317,39.121875,34.183206,34.848685,31.092004,33.499627,31.693203,30.929293,30.173875,29.358919,27.885150,30.302089,30.929752,27.858861,32.787178,28.187500,33.161811,35.062031,32.233333,27.578431,32.801653,33.137931,32.663866,28.641026,29.988235,0.057195
26,"Providence-Warwick, RI-MA",NaN,NaN,45.407378,45.948907,48.840815,45.416636,48.004742,47.654191,47.557702,43.055480,44.110866,44.091661,39.341667,38.075224,40.893115,38.907300,37.089001,33.052526,33.931611,31.190670,29.676134,29.190393,29.317614,39.938636,44.742932,32.713690,37.072787,28.126572,0.043314
23,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",NaN,NaN,56.266134,59.108705,59.042865,57.525469,57.064044,54.791619,57.277661,53.200035,54.868873,53.759419,47.964220,45.748218,46.598614,45.415311,44.767048,45.039646,43.674674,40.490269,39.413405,37.624584,37.475346,37.118793,39.829445,35.627998,41.822321,34.208422,0.037661
33,"San Jose-Sunnyvale-Santa Clara, CA",NaN,NaN,70.095029,60.921498,55.874278,58.161128,52.137928,53.460625,52.559583,48.733452,40.143707,43.193802,38.649917,44.155340,47.716102,43.531073,46.824000,44.563025,48.102564,41.178947,45.837838,48.592000,38.774194,48.235772,41.655738,44.641667,38.162393,NaN,0.037344
24,"Pittsburgh, PA",NaN,NaN,62.613115,60.804772,62.694098,59.649530,59.477979,59.694072,62.271141,57.155039,59.585515,55.715228,52.135186,53.408779,50.090263,48.569181,46.596011,46.955749,46.280768,44.855678,46.723997,44.329551,43.118617,39.453172,44.183065,40.386488,44.100491,36.342984,0.036090
1,"Baltimore-Columbia-Towson, MD",NaN,NaN,62.824925,61.402066,60.354261,59.129313,57.382264,58.145234,59.499710,55.584224,56.180278,54.016698,48.428399,47.844782,47.295553,46.067550,43.458322,43.787059,44.306648,40.857023,38.760179,37.504124,39.591275,33.790063,39.098485,34.339441,44.005513,34.086339,0.031239
39,"Urban Honolulu, HI",NaN,NaN,24.142399,22.755795,24.207283,23.000198,24.238941,21.292307,23.191221,21.807081,21.912940,26.357724,26.744444,19.740741,18.721739,20.754386,19.921739,NaN,NaN,NaN,NaN,24.009524,19.943925,19.818116,17.208333,21.404520,19.264921,19.491071,0.028673
8,"Detroit-Warren-Dearborn, MI",NaN,NaN,59.202340,60.974083,61.262894,60.058202,60.204629,58.324330,60.539365,53.755833,54.485865,50.023950,46.036424,43.947819,44.440858,46.000165,43.162480,45.802065,45.004383,41.982959,40.880553,42.244864,40.573002,37.569095,42.449735,39.207912,44.791150,38.160211,0.017465
35,"St. Louis, MO-IL",NaN,NaN,63.363965,63.162146,60.783063,61.278575,58.883231,56.307124,62.496751,56.485199,58.452735,54.099829,51.365480,55.159257,53.191957,48.584951,50.063260,50.637724,47.554339,44.471235,44.331312,47.608503,46.296570,45.976563,45.861047,45.320369,46.761845,40.939175,0.004174
16,"Memphis, TN-MS-AR",NaN,NaN,61.513343,58.817803,54.658592,54.053019,54.205813,52.998757,56.762728,54.849495,54.293949,52.534662,47.421383,50.831780,49.987681,47.622951,45.399114,44.202786,42.414804,40.490986,41.747774,42.163459,41.587417,39.047051,40.546573,41.336095,44.609903,41.997235,0.003435
14,"Los Angeles-Long Beach-Anaheim, CA",NaN,NaN,72.399439,68.359661,69.317498,69.013847,65.299108,62.783797,60.427711,56.959251,57.974208,55.071509,53.689529,48.538945,49.902546,48.388306,50.611558,54.210913,48.063064,48.146789,50.333665,50.932957,45.918922,53.079805,51.674487,49.678424,47.737663,44.718164,-0.003680
20,"New York-Newark-Jersey City, NY-NJ-PA",NaN,NaN,57.063061,57.740361,56.302782,55.604058,55.357104,53.322619,57.106314,50.871693,53.594410,51.796663,44.927129,43.533207,46.032854,44.664274,42.372420,43.150256,42.682005,39.181181,38.691812,38.899645,37.448864,37.652707,38.965385,36.004929,41.138967,32.578617,-0.005453
4,"Chicago-Naperville-Elgin, IL-IN-WI",57.121951,64.817948,61.906111,61.029117,61.541239,59.300711,58.109288,55.064670,60.733486,54.565680,57.362744,50.786457,49.275134,51.518536,50.429847,48.988311,48.564876,47.810368,46.145483,42.426197,41.608099,45.248039,43.272777,43.787079,45.135499,44.089014,47.185000,38.336416,-0.016487
30,"Rochester, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.729167,51.281818,42.966387,43.361345,42.547826,38.085470,39.324324,42.021978,42.504854,36.170940,37.016667,38.873639,32.853258,34.727959,35.834030,33.671665,30.760940,35.087002,30.893964,38.236017,29.625000,-0.021895
11,"Hartford-West Hartford-East Hartford, CT",NaN,NaN,47.772321,47.238255,51.399381,50.013559,50.573964,48.032738,49.487179,46.089231,44.478754,46.870080,40.864988,38.408042,42.847394,38.868874,38.522847,38.185724,40.932065,35.535394,33.816686,33.891371,29.815055,32.719298,35.180328,31.631579,36.700000,28.193548,-0.058550

In [232]:
merge = merge.drop(columns='pop_pct_change')

## Turning the data into long format for import to Observable as json

In [233]:
# Reshape with melt (keeping 'CBSA Name' and 'pop_pct_change' intact)
tidy_df = merge.melt(
    id_vars="CBSA Name",
    var_name="year",
    value_name="value"
)

In [234]:
tidy_df

                                           CBSA Name  year      value
0                                         Fresno, CA  1997        NaN
1                      Orlando-Kissimmee-Sanford, FL  1997        NaN
2                                        Raleigh, NC  1997        NaN
3                                   Jacksonville, FL  1997        NaN
4     Nashville-Davidson--Murfreesboro--Franklin, TN  1997        NaN
...                                              ...   ...        ...
1143              Los Angeles-Long Beach-Anaheim, CA  2024  44.718164
1144           New York-Newark-Jersey City, NY-NJ-PA  2024  32.578617
1145              Chicago-Naperville-Elgin, IL-IN-WI  2024  38.336416
1146                                   Rochester, NY  2024  29.625000
1147        Hartford-West Hartford-East Hartford, CT  2024  28.193548

[1148 rows x 3 columns]

In [239]:
tidy_df.dtypes

CBSA Name     object
year           int64
value        float64
dtype: object

In [235]:
import numpy as np

tidy_df.loc[tidy_df["year"].isin([1997, 1998]), "value"] = np.nan

In [236]:
tidy_df = tidy_df.fillna(0)

/var/folders/mb/f5zh4qyd6sbf171lrlnmff040000gn/T/ipykernel_9844/3674079045.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tidy_df = tidy_df.fillna(0)

In [240]:
tidy_df['date'] = pd.to_datetime(tidy_df['year'].astype(str) + '-01-01')

In [241]:
tidy_df.to_csv('top_growing_large_metros_pm25.csv',index=False)

In [242]:
tidy_df.to_json("air_quality.json", orient="records")